<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Micro: /mnt/c/Users/abell/Documents/GitHub/NRE-Micro/src/ROM/Manager/NRE_RomManagerInl.hpp Source File</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="files.php"><span>File&#160;List</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_68267d1309a1af8e8297ef4c3efbcdba.php">src</a></li><li class="navelem"><a class="el" href="dir_b8c575fbce9e88769cd973c21567fab3.php">ROM</a></li><li class="navelem"><a class="el" href="dir_6fd6a1e3d1cabd12d4d22f426f330e02.php">Manager</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE_RomManagerInl.hpp</div>  </div>
</div><!--header-->
<div class="contents">
<a href="_n_r_e___rom_manager_inl_8hpp.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;</div><div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;    <span class="keyword">namespace </span><a class="code" href="namespace_n_r_e.php">NRE</a> {</div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;        <span class="keyword">namespace </span><a class="code" href="namespace_micro.php">Micro</a> {</div><div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;</div><div class="line"><a name="l00013"></a><span class="lineno">   13</span>&#160;            <span class="keyword">inline</span> RomManager::RomManager() : currentPtr(1) {</div><div class="line"><a name="l00014"></a><span class="lineno">   14</span>&#160;            }</div><div class="line"><a name="l00015"></a><span class="lineno">   15</span>&#160;</div><div class="line"><a name="l00016"></a><span class="lineno">   16</span>&#160;            <span class="keyword">template</span> &lt;<span class="keyword">class</span> T&gt;</div><div class="line"><a name="l00017"></a><span class="lineno">   17</span>&#160;            <span class="keyword">inline</span> <span class="keywordtype">void</span> RomManager::addData(ObservedData&lt;T&gt;&amp; data) {</div><div class="line"><a name="l00018"></a><span class="lineno">   18</span>&#160;                objects.push_back(&amp;data);</div><div class="line"><a name="l00019"></a><span class="lineno">   19</span>&#160;                data.ptr = currentPtr;</div><div class="line"><a name="l00020"></a><span class="lineno">   20</span>&#160;                currentPtr += data.getSize();</div><div class="line"><a name="l00021"></a><span class="lineno">   21</span>&#160;            }</div><div class="line"><a name="l00022"></a><span class="lineno">   22</span>&#160;</div><div class="line"><a name="l00023"></a><span class="lineno">   23</span>&#160;            <span class="keyword">inline</span> <span class="keywordtype">void</span> RomManager::clearROM() {</div><div class="line"><a name="l00024"></a><span class="lineno">   24</span>&#160;                memset(&amp;EEPROM[1], FILL_SYMBOL, MAX_ADDR - 1);</div><div class="line"><a name="l00025"></a><span class="lineno">   25</span>&#160;                EEPROM[0] = START_SYMBOL;</div><div class="line"><a name="l00026"></a><span class="lineno">   26</span>&#160;                EEPROM.commit();</div><div class="line"><a name="l00027"></a><span class="lineno">   27</span>&#160;            }</div><div class="line"><a name="l00028"></a><span class="lineno">   28</span>&#160;</div><div class="line"><a name="l00029"></a><span class="lineno">   29</span>&#160;            <span class="keyword">inline</span> <span class="keywordtype">void</span> RomManager::loadROM() {</div><div class="line"><a name="l00030"></a><span class="lineno">   30</span>&#160;                <span class="keywordflow">for</span> (<a class="code" href="class_n_r_e_1_1_micro_1_1_abstract_data.php#ace46a0e36fc28878ffa0e26c7bd27a10">AbstractData</a>* obj : objects) {</div><div class="line"><a name="l00031"></a><span class="lineno">   31</span>&#160;                    obj-&gt;read(&amp;EEPROM[obj-&gt;ptr]);</div><div class="line"><a name="l00032"></a><span class="lineno">   32</span>&#160;                }</div><div class="line"><a name="l00033"></a><span class="lineno">   33</span>&#160;            }</div><div class="line"><a name="l00034"></a><span class="lineno">   34</span>&#160;</div><div class="line"><a name="l00035"></a><span class="lineno">   35</span>&#160;            <span class="keyword">inline</span> <span class="keywordtype">void</span> RomManager::resetROM() {</div><div class="line"><a name="l00036"></a><span class="lineno">   36</span>&#160;                EEPROM[0] = RESET_SYMBOl;</div><div class="line"><a name="l00037"></a><span class="lineno">   37</span>&#160;                EEPROM.commit();</div><div class="line"><a name="l00038"></a><span class="lineno">   38</span>&#160;            }</div><div class="line"><a name="l00039"></a><span class="lineno">   39</span>&#160;</div><div class="line"><a name="l00040"></a><span class="lineno">   40</span>&#160;            <span class="keyword">template</span> &lt;&gt;</div><div class="line"><a name="l00041"></a><span class="lineno">   41</span>&#160;            <span class="keyword">inline</span> <span class="keywordtype">void</span> RomManager::write(String* data, <span class="keywordtype">int</span> addr) {</div><div class="line"><a name="l00042"></a><span class="lineno">   42</span>&#160;                memcpy(reinterpret_cast &lt;uint8_t*&gt; (data), &amp;EEPROM[addr], data-&gt;length());</div><div class="line"><a name="l00043"></a><span class="lineno">   43</span>&#160;                EEPROM.commit();</div><div class="line"><a name="l00044"></a><span class="lineno">   44</span>&#160;            }</div><div class="line"><a name="l00045"></a><span class="lineno">   45</span>&#160;</div><div class="line"><a name="l00046"></a><span class="lineno">   46</span>&#160;            <span class="keyword">template</span> &lt;<span class="keyword">class</span> T&gt;</div><div class="line"><a name="l00047"></a><span class="lineno">   47</span>&#160;            <span class="keyword">inline</span> <span class="keywordtype">void</span> RomManager::write(T* data, <span class="keywordtype">int</span> addr) {</div><div class="line"><a name="l00048"></a><span class="lineno">   48</span>&#160;                EEPROM.put&lt;T&gt;(addr, *data);</div><div class="line"><a name="l00049"></a><span class="lineno">   49</span>&#160;                EEPROM.commit();</div><div class="line"><a name="l00050"></a><span class="lineno">   50</span>&#160;            }</div><div class="line"><a name="l00051"></a><span class="lineno">   51</span>&#160;</div><div class="line"><a name="l00052"></a><span class="lineno">   52</span>&#160;            <span class="keyword">inline</span> <span class="keywordtype">void</span> RomManager::setup() {</div><div class="line"><a name="l00053"></a><span class="lineno">   53</span>&#160;                EEPROM.begin(MAX_ADDR);</div><div class="line"><a name="l00054"></a><span class="lineno">   54</span>&#160;                <span class="keywordflow">if</span> (EEPROM[0] == START_SYMBOL) {</div><div class="line"><a name="l00055"></a><span class="lineno">   55</span>&#160;                    loadROM();</div><div class="line"><a name="l00056"></a><span class="lineno">   56</span>&#160;                } <span class="keywordflow">else</span> {</div><div class="line"><a name="l00057"></a><span class="lineno">   57</span>&#160;                    clearROM();</div><div class="line"><a name="l00058"></a><span class="lineno">   58</span>&#160;                }</div><div class="line"><a name="l00059"></a><span class="lineno">   59</span>&#160;            }</div><div class="line"><a name="l00060"></a><span class="lineno">   60</span>&#160;</div><div class="line"><a name="l00061"></a><span class="lineno">   61</span>&#160;        }</div><div class="line"><a name="l00062"></a><span class="lineno">   62</span>&#160;    }</div><div class="ttc" id="namespace_micro_php"><div class="ttname"><a href="namespace_micro.php">Micro</a></div><div class="ttdoc">Micro&amp;#39;s API. </div></div>
<div class="ttc" id="namespace_n_r_e_php"><div class="ttname"><a href="namespace_n_r_e.php">NRE</a></div><div class="ttdoc">The NearlyRealEngine&amp;#39;s global namespace. </div><div class="ttdef"><b>Definition:</b> NRE_AbstractModule.cpp:12</div></div>
<div class="ttc" id="class_n_r_e_1_1_micro_1_1_abstract_data_php_ace46a0e36fc28878ffa0e26c7bd27a10"><div class="ttname"><a href="class_n_r_e_1_1_micro_1_1_abstract_data.php#ace46a0e36fc28878ffa0e26c7bd27a10">NRE::Micro::AbstractData::AbstractData</a></div><div class="ttdeci">AbstractData()=default</div></div>
</div><!-- fragment --></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
