<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Micro: /mnt/c/Users/abell/Documents/GitHub/NRE-Micro/src/WiFi/Manager/NRE_WiFiManagerInl.hpp Source File</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="files.php"><span>File&#160;List</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_68267d1309a1af8e8297ef4c3efbcdba.php">src</a></li><li class="navelem"><a class="el" href="dir_e5889a8f6e66136a451bc59a49215add.php">WiFi</a></li><li class="navelem"><a class="el" href="dir_12c5bfa1a1339ec11c81ed7328743586.php">Manager</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE_WiFiManagerInl.hpp</div>  </div>
</div><!--header-->
<div class="contents">
<a href="_n_r_e___wi_fi_manager_inl_8hpp.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;</div><div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;    <span class="keyword">namespace </span><a class="code" href="namespace_n_r_e.php">NRE</a> {</div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;        <span class="keyword">namespace </span><a class="code" href="namespace_micro.php">Micro</a> {</div><div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;</div><div class="line"><a name="l00013"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_micro_1_1_wi_fi_manager.php#a9a0f001e36e296ed8036456560e741cd">   13</a></span>&#160;            <span class="keyword">inline</span> <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_micro_1_1_wi_fi_manager.php#a9a0f001e36e296ed8036456560e741cd">WiFiManager::setAPOnSetup</a>(String <span class="keyword">const</span>&amp; name, String <span class="keyword">const</span>&amp; pwd) {</div><div class="line"><a name="l00014"></a><span class="lineno">   14</span>&#160;                hotspot = {name, pwd};</div><div class="line"><a name="l00015"></a><span class="lineno">   15</span>&#160;                launchAPOnSetup = <span class="keyword">true</span>;</div><div class="line"><a name="l00016"></a><span class="lineno">   16</span>&#160;            }</div><div class="line"><a name="l00017"></a><span class="lineno">   17</span>&#160;</div><div class="line"><a name="l00018"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_micro_1_1_wi_fi_manager.php#a3ccf7a64ec6ee3718b2eddf18c687c15">   18</a></span>&#160;            <span class="keyword">inline</span> <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_micro_1_1_wi_fi_manager.php#a3ccf7a64ec6ee3718b2eddf18c687c15">WiFiManager::addKnownNetwork</a>(String <span class="keyword">const</span>&amp; name, String <span class="keyword">const</span>&amp; pwd) {</div><div class="line"><a name="l00019"></a><span class="lineno">   19</span>&#160;                networks.push_back({name, pwd});</div><div class="line"><a name="l00020"></a><span class="lineno">   20</span>&#160;            }</div><div class="line"><a name="l00021"></a><span class="lineno">   21</span>&#160;</div><div class="line"><a name="l00022"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_micro_1_1_wi_fi_manager.php#a4673d981d3a99bf6c6fe0926fb5bb8a6">   22</a></span>&#160;            <span class="keyword">inline</span> <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_micro_1_1_wi_fi_manager.php#a4673d981d3a99bf6c6fe0926fb5bb8a6">WiFiManager::setup</a>() {</div><div class="line"><a name="l00023"></a><span class="lineno">   23</span>&#160;                connected = <span class="keyword">false</span>;</div><div class="line"><a name="l00024"></a><span class="lineno">   24</span>&#160;</div><div class="line"><a name="l00025"></a><span class="lineno">   25</span>&#160;                WiFi.scanNetworks(<span class="keyword">false</span>, <span class="keyword">false</span>);</div><div class="line"><a name="l00026"></a><span class="lineno">   26</span>&#160;                scannedNetworks = WiFi.scanComplete();</div><div class="line"><a name="l00027"></a><span class="lineno">   27</span>&#160;</div><div class="line"><a name="l00028"></a><span class="lineno">   28</span>&#160;                <span class="keywordtype">int</span> current = 0;</div><div class="line"><a name="l00029"></a><span class="lineno">   29</span>&#160;                <span class="keywordflow">while</span> (!connected &amp;&amp; current &lt; networks.size()) {</div><div class="line"><a name="l00030"></a><span class="lineno">   30</span>&#160;                    <span class="keywordtype">int</span> scanned = 0;</div><div class="line"><a name="l00031"></a><span class="lineno">   31</span>&#160;                    <span class="keywordflow">while</span> (!connected &amp;&amp; scanned &lt; scannedNetworks) {</div><div class="line"><a name="l00032"></a><span class="lineno">   32</span>&#160;                        <span class="keywordflow">if</span> (WiFi.SSID(scanned) == networks[current].name) {</div><div class="line"><a name="l00033"></a><span class="lineno">   33</span>&#160;                            WiFi.begin(networks[current].name, networks[current].pwd);</div><div class="line"><a name="l00034"></a><span class="lineno">   34</span>&#160;                            connected = <span class="keyword">true</span>;</div><div class="line"><a name="l00035"></a><span class="lineno">   35</span>&#160;                        }</div><div class="line"><a name="l00036"></a><span class="lineno">   36</span>&#160;                        ++scanned;</div><div class="line"><a name="l00037"></a><span class="lineno">   37</span>&#160;                    }</div><div class="line"><a name="l00038"></a><span class="lineno">   38</span>&#160;                    ++current;</div><div class="line"><a name="l00039"></a><span class="lineno">   39</span>&#160;                }</div><div class="line"><a name="l00040"></a><span class="lineno">   40</span>&#160;</div><div class="line"><a name="l00041"></a><span class="lineno">   41</span>&#160;                <span class="keywordflow">if</span> (launchAPOnSetup) {</div><div class="line"><a name="l00042"></a><span class="lineno">   42</span>&#160;                    WiFi.softAP(hotspot.<a class="code" href="struct_n_r_e_1_1_micro_1_1_network.php#ad3a8ea4505079c79e77f3748fc854b85">name</a>, hotspot.<a class="code" href="struct_n_r_e_1_1_micro_1_1_network.php#a1b007d38ac2e4fbf2c82297bd5ab1bf3">pwd</a>);</div><div class="line"><a name="l00043"></a><span class="lineno">   43</span>&#160;                }</div><div class="line"><a name="l00044"></a><span class="lineno">   44</span>&#160;            }</div><div class="line"><a name="l00045"></a><span class="lineno">   45</span>&#160;</div><div class="line"><a name="l00046"></a><span class="lineno">   46</span>&#160;        }</div><div class="line"><a name="l00047"></a><span class="lineno">   47</span>&#160;    }</div><div class="ttc" id="class_n_r_e_1_1_micro_1_1_wi_fi_manager_php_a4673d981d3a99bf6c6fe0926fb5bb8a6"><div class="ttname"><a href="class_n_r_e_1_1_micro_1_1_wi_fi_manager.php#a4673d981d3a99bf6c6fe0926fb5bb8a6">NRE::Micro::WiFiManager::setup</a></div><div class="ttdeci">void setup() override</div><div class="ttdef"><b>Definition:</b> NRE_WiFiManagerInl.hpp:22</div></div>
<div class="ttc" id="namespace_micro_php"><div class="ttname"><a href="namespace_micro.php">Micro</a></div><div class="ttdoc">Micro&amp;#39;s API. </div></div>
<div class="ttc" id="class_n_r_e_1_1_micro_1_1_wi_fi_manager_php_a3ccf7a64ec6ee3718b2eddf18c687c15"><div class="ttname"><a href="class_n_r_e_1_1_micro_1_1_wi_fi_manager.php#a3ccf7a64ec6ee3718b2eddf18c687c15">NRE::Micro::WiFiManager::addKnownNetwork</a></div><div class="ttdeci">void addKnownNetwork(String const &amp;name, String const &amp;pwd)</div><div class="ttdef"><b>Definition:</b> NRE_WiFiManagerInl.hpp:18</div></div>
<div class="ttc" id="class_n_r_e_1_1_micro_1_1_wi_fi_manager_php_a9a0f001e36e296ed8036456560e741cd"><div class="ttname"><a href="class_n_r_e_1_1_micro_1_1_wi_fi_manager.php#a9a0f001e36e296ed8036456560e741cd">NRE::Micro::WiFiManager::setAPOnSetup</a></div><div class="ttdeci">void setAPOnSetup(String const &amp;name, String const &amp;pwd)</div><div class="ttdef"><b>Definition:</b> NRE_WiFiManagerInl.hpp:13</div></div>
<div class="ttc" id="struct_n_r_e_1_1_micro_1_1_network_php_ad3a8ea4505079c79e77f3748fc854b85"><div class="ttname"><a href="struct_n_r_e_1_1_micro_1_1_network.php#ad3a8ea4505079c79e77f3748fc854b85">NRE::Micro::Network::name</a></div><div class="ttdeci">String name</div><div class="ttdef"><b>Definition:</b> NRE_WiFiManager.hpp:33</div></div>
<div class="ttc" id="namespace_n_r_e_php"><div class="ttname"><a href="namespace_n_r_e.php">NRE</a></div><div class="ttdoc">The NearlyRealEngine&amp;#39;s global namespace. </div><div class="ttdef"><b>Definition:</b> NRE_AbstractModule.cpp:12</div></div>
<div class="ttc" id="struct_n_r_e_1_1_micro_1_1_network_php_a1b007d38ac2e4fbf2c82297bd5ab1bf3"><div class="ttname"><a href="struct_n_r_e_1_1_micro_1_1_network.php#a1b007d38ac2e4fbf2c82297bd5ab1bf3">NRE::Micro::Network::pwd</a></div><div class="ttdeci">String pwd</div><div class="ttdef"><b>Definition:</b> NRE_WiFiManager.hpp:34</div></div>
</div><!-- fragment --></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
