<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Micro: /mnt/c/Users/abell/Documents/GitHub/NRE-Micro/src/Core/Module/NRE_Module.hpp Source File</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="files.php"><span>File&#160;List</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_68267d1309a1af8e8297ef4c3efbcdba.php">src</a></li><li class="navelem"><a class="el" href="dir_a2f0e5642e47e7ed59fe0f0829eafb5f.php">Core</a></li><li class="navelem"><a class="el" href="dir_b00fbd6cf7f8e36694ce8c1205bd4029.php">Module</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE_Module.hpp</div>  </div>
</div><!--header-->
<div class="contents">
<a href="_n_r_e___module_8hpp.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;</div><div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;<span class="preprocessor">    #pragma once</span></div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;</div><div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;<span class="preprocessor">    #include &quot;<a class="code" href="_n_r_e___abstract_module_8hpp.php">NRE_AbstractModule.hpp</a>&quot;</span></div><div class="line"><a name="l00013"></a><span class="lineno">   13</span>&#160;<span class="preprocessor">    #include &quot;../NRE_Core.hpp&quot;</span></div><div class="line"><a name="l00014"></a><span class="lineno">   14</span>&#160;</div><div class="line"><a name="l00019"></a><span class="lineno">   19</span>&#160;    <span class="keyword">namespace </span><a class="code" href="namespace_n_r_e.php">NRE</a> {</div><div class="line"><a name="l00024"></a><span class="lineno">   24</span>&#160;        <span class="keyword">namespace </span><a class="code" href="namespace_micro.php">Micro</a> {</div><div class="line"><a name="l00025"></a><span class="lineno">   25</span>&#160;</div><div class="line"><a name="l00030"></a><span class="lineno">   30</span>&#160;            <span class="keyword">template</span> &lt;<span class="keyword">class</span> SubModule&gt;</div><div class="line"><a name="l00031"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_micro_1_1_module.php">   31</a></span>&#160;            <span class="keyword">class </span><a class="code" href="class_n_r_e_1_1_micro_1_1_module.php">Module</a> : <span class="keyword">public</span> <a class="code" href="class_n_r_e_1_1_micro_1_1_abstract_module.php">AbstractModule</a> {</div><div class="line"><a name="l00032"></a><span class="lineno">   32</span>&#160;                <span class="keyword">public</span> :   <span class="comment">// Methods</span></div><div class="line"><a name="l00033"></a><span class="lineno">   33</span>&#160;                    <span class="comment">//## Constructor ##//</span></div><div class="line"><a name="l00037"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_micro_1_1_module.php#ab8051683526e308ef6d0c878ccfb9fe2">   37</a></span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_micro_1_1_module.php#ab8051683526e308ef6d0c878ccfb9fe2">Module</a>() {</div><div class="line"><a name="l00038"></a><span class="lineno">   38</span>&#160;                            <a class="code" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#a30db23a789e19edbe1547c1f3b38f85c">MicroManager::add</a>(static_cast &lt;SubModule*&gt; (<span class="keyword">this</span>));</div><div class="line"><a name="l00039"></a><span class="lineno">   39</span>&#160;                        }</div><div class="line"><a name="l00040"></a><span class="lineno">   40</span>&#160;</div><div class="line"><a name="l00041"></a><span class="lineno">   41</span>&#160;                    <span class="comment">//## Deconstructor ##//</span></div><div class="line"><a name="l00045"></a><span class="lineno">   45</span>&#160;<span class="comment"></span>                        <span class="keyword">virtual</span> <a class="code" href="class_n_r_e_1_1_micro_1_1_module.php#ab4e431b60f84d4b499c9315cf4502f4b">~Module</a>() = <span class="keywordflow">default</span>;</div><div class="line"><a name="l00046"></a><span class="lineno">   46</span>&#160;</div><div class="line"><a name="l00047"></a><span class="lineno">   47</span>&#160;                <span class="keyword">public</span> :    <span class="comment">// Static</span></div><div class="line"><a name="l00051"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_micro_1_1_module.php#a6d9a8c837f180ffd064224d06d9f42e4">   51</a></span>&#160;<span class="comment"></span>                    <span class="keyword">static</span> ModuleId <a class="code" href="class_n_r_e_1_1_micro_1_1_module.php#a6d9a8c837f180ffd064224d06d9f42e4">getId</a>() {</div><div class="line"><a name="l00052"></a><span class="lineno">   52</span>&#160;                        <span class="keyword">static</span> ModuleId <span class="keywordtype">id</span> = <a class="code" href="class_n_r_e_1_1_micro_1_1_abstract_module.php#a95d15910d0d4e77aa08063fe383ff8dc">counter</a>++;</div><div class="line"><a name="l00053"></a><span class="lineno">   53</span>&#160;                        <span class="keywordflow">return</span> id;</div><div class="line"><a name="l00054"></a><span class="lineno">   54</span>&#160;                    }</div><div class="line"><a name="l00055"></a><span class="lineno">   55</span>&#160;            };</div><div class="line"><a name="l00056"></a><span class="lineno">   56</span>&#160;</div><div class="line"><a name="l00057"></a><span class="lineno">   57</span>&#160;        }</div><div class="line"><a name="l00058"></a><span class="lineno">   58</span>&#160;    }</div><div class="ttc" id="class_n_r_e_1_1_micro_1_1_module_php_ab4e431b60f84d4b499c9315cf4502f4b"><div class="ttname"><a href="class_n_r_e_1_1_micro_1_1_module.php#ab4e431b60f84d4b499c9315cf4502f4b">NRE::Micro::Module::~Module</a></div><div class="ttdeci">virtual ~Module()=default</div></div>
<div class="ttc" id="class_n_r_e_1_1_micro_1_1_module_php_ab8051683526e308ef6d0c878ccfb9fe2"><div class="ttname"><a href="class_n_r_e_1_1_micro_1_1_module.php#ab8051683526e308ef6d0c878ccfb9fe2">NRE::Micro::Module::Module</a></div><div class="ttdeci">Module()</div><div class="ttdef"><b>Definition:</b> NRE_Module.hpp:37</div></div>
<div class="ttc" id="namespace_micro_php"><div class="ttname"><a href="namespace_micro.php">Micro</a></div><div class="ttdoc">Micro&amp;#39;s API. </div></div>
<div class="ttc" id="class_n_r_e_1_1_micro_1_1_module_php_a6d9a8c837f180ffd064224d06d9f42e4"><div class="ttname"><a href="class_n_r_e_1_1_micro_1_1_module.php#a6d9a8c837f180ffd064224d06d9f42e4">NRE::Micro::Module::getId</a></div><div class="ttdeci">static ModuleId getId()</div><div class="ttdef"><b>Definition:</b> NRE_Module.hpp:51</div></div>
<div class="ttc" id="_n_r_e___abstract_module_8hpp_php"><div class="ttname"><a href="_n_r_e___abstract_module_8hpp.php">NRE_AbstractModule.hpp</a></div><div class="ttdoc">Declaration of Micro&amp;#39;s API&amp;#39;s Core Object : AbstractModule. </div></div>
<div class="ttc" id="class_n_r_e_1_1_micro_1_1_abstract_module_php"><div class="ttname"><a href="class_n_r_e_1_1_micro_1_1_abstract_module.php">NRE::Micro::AbstractModule</a></div><div class="ttdoc">Represent an abstract module used to active a certain part of the framework. </div><div class="ttdef"><b>Definition:</b> NRE_AbstractModule.hpp:29</div></div>
<div class="ttc" id="class_n_r_e_1_1_micro_1_1_micro_manager_php_a30db23a789e19edbe1547c1f3b38f85c"><div class="ttname"><a href="class_n_r_e_1_1_micro_1_1_micro_manager.php#a30db23a789e19edbe1547c1f3b38f85c">NRE::Micro::MicroManager::add</a></div><div class="ttdeci">static void add(SubModule *module)</div><div class="ttdef"><b>Definition:</b> NRE_CoreInl.hpp:42</div></div>
<div class="ttc" id="namespace_n_r_e_php"><div class="ttname"><a href="namespace_n_r_e.php">NRE</a></div><div class="ttdoc">The NearlyRealEngine&amp;#39;s global namespace. </div><div class="ttdef"><b>Definition:</b> NRE_AbstractModule.cpp:12</div></div>
<div class="ttc" id="class_n_r_e_1_1_micro_1_1_abstract_module_php_a95d15910d0d4e77aa08063fe383ff8dc"><div class="ttname"><a href="class_n_r_e_1_1_micro_1_1_abstract_module.php#a95d15910d0d4e77aa08063fe383ff8dc">NRE::Micro::AbstractModule::counter</a></div><div class="ttdeci">static ModuleId counter</div><div class="ttdef"><b>Definition:</b> NRE_AbstractModule.hpp:84</div></div>
<div class="ttc" id="class_n_r_e_1_1_micro_1_1_module_php"><div class="ttname"><a href="class_n_r_e_1_1_micro_1_1_module.php">NRE::Micro::Module</a></div><div class="ttdoc">Represent a module interface to create framework sub module. </div><div class="ttdef"><b>Definition:</b> NRE_Module.hpp:31</div></div>
</div><!-- fragment --></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
