<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Micro: /mnt/c/Users/abell/Documents/GitHub/NRE-Micro/src/LED/Controller/NRE_LedInl.hpp Source File</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="files.php"><span>File&#160;List</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_68267d1309a1af8e8297ef4c3efbcdba.php">src</a></li><li class="navelem"><a class="el" href="dir_6b864641f3cab9a7d09fa51df47d12f6.php">LED</a></li><li class="navelem"><a class="el" href="dir_57532afd96e118b5b73bacfc38254880.php">Controller</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE_LedInl.hpp</div>  </div>
</div><!--header-->
<div class="contents">
<a href="_n_r_e___led_inl_8hpp.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;</div><div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;    <span class="keyword">namespace </span><a class="code" href="namespace_n_r_e.php">NRE</a> {</div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;        <span class="keyword">namespace </span><a class="code" href="namespace_micro.php">Micro</a> {</div><div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;</div><div class="line"><a name="l00013"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_micro_1_1_led.php#a8b166a24c3fe7c0beb4dd50e4015f4d8">   13</a></span>&#160;            <span class="keyword">inline</span> <a class="code" href="class_n_r_e_1_1_micro_1_1_led.php#a3d47f7f1317221084b4571ae261c34f8">Led::Led</a>(LedId i, <a class="code" href="class_n_r_e_1_1_micro_1_1_led_controller.php">LedController</a>* ctr) : id(i), controller(ctr) {</div><div class="line"><a name="l00014"></a><span class="lineno">   14</span>&#160;            }</div><div class="line"><a name="l00015"></a><span class="lineno">   15</span>&#160;</div><div class="line"><a name="l00016"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_micro_1_1_led.php#a25bef4d3e5d9463190c55e4a2bfd447c">   16</a></span>&#160;            <span class="keyword">inline</span> <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_micro_1_1_led.php#a25bef4d3e5d9463190c55e4a2bfd447c">Led::update</a>(<a class="code" href="class_n_r_e_1_1_micro_1_1_color.php">Color</a> <span class="keyword">const</span>&amp; color) {</div><div class="line"><a name="l00017"></a><span class="lineno">   17</span>&#160;                <a class="code" href="class_n_r_e_1_1_micro_1_1_led.php#a84e8281436fa31ffbb4eb39ef6aaba4b">setColor</a>(color);</div><div class="line"><a name="l00018"></a><span class="lineno">   18</span>&#160;                controller-&gt;<a class="code" href="class_n_r_e_1_1_micro_1_1_led_controller.php#a0b8a39b1a9e132de0f7c2fc5127e8ab0">turnOn</a>(<span class="keywordtype">id</span>);</div><div class="line"><a name="l00019"></a><span class="lineno">   19</span>&#160;            }</div><div class="line"><a name="l00020"></a><span class="lineno">   20</span>&#160;</div><div class="line"><a name="l00021"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_micro_1_1_led.php#a922510060cd8947bad521fa47a5ee028">   21</a></span>&#160;            <span class="keyword">inline</span> <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_micro_1_1_led.php#a922510060cd8947bad521fa47a5ee028">Led::turnOff</a>()<span class="keyword"> const </span>{</div><div class="line"><a name="l00022"></a><span class="lineno">   22</span>&#160;                controller-&gt;<a class="code" href="class_n_r_e_1_1_micro_1_1_led_controller.php#ab91228876528d9d66b1aa35b078b78e1">turnOff</a>(<span class="keywordtype">id</span>);</div><div class="line"><a name="l00023"></a><span class="lineno">   23</span>&#160;            }</div><div class="line"><a name="l00024"></a><span class="lineno">   24</span>&#160;</div><div class="line"><a name="l00025"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_micro_1_1_led.php#a8834d8f177b8ab098b107020de280ef2">   25</a></span>&#160;            <span class="keyword">inline</span> <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_micro_1_1_led.php#a8834d8f177b8ab098b107020de280ef2">Led::turnOn</a>()<span class="keyword"> const </span>{</div><div class="line"><a name="l00026"></a><span class="lineno">   26</span>&#160;                controller-&gt;<a class="code" href="class_n_r_e_1_1_micro_1_1_led_controller.php#a0b8a39b1a9e132de0f7c2fc5127e8ab0">turnOn</a>(<span class="keywordtype">id</span>);</div><div class="line"><a name="l00027"></a><span class="lineno">   27</span>&#160;            }</div><div class="line"><a name="l00028"></a><span class="lineno">   28</span>&#160;</div><div class="line"><a name="l00029"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_micro_1_1_led.php#a144cb7e189a4850cf3f5c045c45d5fab">   29</a></span>&#160;            <span class="keyword">inline</span> CompressedColor <a class="code" href="class_n_r_e_1_1_micro_1_1_led.php#a144cb7e189a4850cf3f5c045c45d5fab">Led::getColor</a>()<span class="keyword"> const </span>{</div><div class="line"><a name="l00030"></a><span class="lineno">   30</span>&#160;                <span class="keywordflow">return</span> current.get().getColor();</div><div class="line"><a name="l00031"></a><span class="lineno">   31</span>&#160;            }</div><div class="line"><a name="l00032"></a><span class="lineno">   32</span>&#160;</div><div class="line"><a name="l00033"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_micro_1_1_led.php#a84e8281436fa31ffbb4eb39ef6aaba4b">   33</a></span>&#160;            <span class="keyword">inline</span> <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_micro_1_1_led.php#a84e8281436fa31ffbb4eb39ef6aaba4b">Led::setColor</a>(<a class="code" href="class_n_r_e_1_1_micro_1_1_color.php">Color</a> <span class="keyword">const</span>&amp; color) {</div><div class="line"><a name="l00034"></a><span class="lineno">   34</span>&#160;                current = color;</div><div class="line"><a name="l00035"></a><span class="lineno">   35</span>&#160;            }</div><div class="line"><a name="l00036"></a><span class="lineno">   36</span>&#160;</div><div class="line"><a name="l00037"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_micro_1_1_led.php#a2624fb34732b14e2eb7f9880c99786cb">   37</a></span>&#160;            <span class="keyword">inline</span> <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_micro_1_1_led.php#a2624fb34732b14e2eb7f9880c99786cb">Led::setColorHandle</a>(std::function&lt;<span class="keywordtype">void</span>(<a class="code" href="class_n_r_e_1_1_micro_1_1_color.php">Color</a>&amp;)&gt; handle) {</div><div class="line"><a name="l00038"></a><span class="lineno">   38</span>&#160;                current.setHandle(handle);</div><div class="line"><a name="l00039"></a><span class="lineno">   39</span>&#160;            }</div><div class="line"><a name="l00040"></a><span class="lineno">   40</span>&#160;</div><div class="line"><a name="l00041"></a><span class="lineno">   41</span>&#160;        }</div><div class="line"><a name="l00042"></a><span class="lineno">   42</span>&#160;    }</div><div class="ttc" id="class_n_r_e_1_1_micro_1_1_led_php_a922510060cd8947bad521fa47a5ee028"><div class="ttname"><a href="class_n_r_e_1_1_micro_1_1_led.php#a922510060cd8947bad521fa47a5ee028">NRE::Micro::Led::turnOff</a></div><div class="ttdeci">void turnOff() const </div><div class="ttdef"><b>Definition:</b> NRE_LedInl.hpp:21</div></div>
<div class="ttc" id="class_n_r_e_1_1_micro_1_1_led_php_a3d47f7f1317221084b4571ae261c34f8"><div class="ttname"><a href="class_n_r_e_1_1_micro_1_1_led.php#a3d47f7f1317221084b4571ae261c34f8">NRE::Micro::Led::Led</a></div><div class="ttdeci">Led()=delete</div></div>
<div class="ttc" id="class_n_r_e_1_1_micro_1_1_color_php"><div class="ttname"><a href="class_n_r_e_1_1_micro_1_1_color.php">NRE::Micro::Color</a></div><div class="ttdoc">Represent a led Color. </div><div class="ttdef"><b>Definition:</b> NRE_Color.hpp:32</div></div>
<div class="ttc" id="class_n_r_e_1_1_micro_1_1_led_php_a25bef4d3e5d9463190c55e4a2bfd447c"><div class="ttname"><a href="class_n_r_e_1_1_micro_1_1_led.php#a25bef4d3e5d9463190c55e4a2bfd447c">NRE::Micro::Led::update</a></div><div class="ttdeci">void update(Color const &amp;color)</div><div class="ttdef"><b>Definition:</b> NRE_LedInl.hpp:16</div></div>
<div class="ttc" id="namespace_micro_php"><div class="ttname"><a href="namespace_micro.php">Micro</a></div><div class="ttdoc">Micro&amp;#39;s API. </div></div>
<div class="ttc" id="class_n_r_e_1_1_micro_1_1_led_controller_php_ab91228876528d9d66b1aa35b078b78e1"><div class="ttname"><a href="class_n_r_e_1_1_micro_1_1_led_controller.php#ab91228876528d9d66b1aa35b078b78e1">NRE::Micro::LedController::turnOff</a></div><div class="ttdeci">void turnOff()</div><div class="ttdef"><b>Definition:</b> NRE_LedControllerInl.hpp:57</div></div>
<div class="ttc" id="class_n_r_e_1_1_micro_1_1_led_php_a2624fb34732b14e2eb7f9880c99786cb"><div class="ttname"><a href="class_n_r_e_1_1_micro_1_1_led.php#a2624fb34732b14e2eb7f9880c99786cb">NRE::Micro::Led::setColorHandle</a></div><div class="ttdeci">void setColorHandle(std::function&lt; void(Color &amp;)&gt; handle)</div><div class="ttdef"><b>Definition:</b> NRE_LedInl.hpp:37</div></div>
<div class="ttc" id="class_n_r_e_1_1_micro_1_1_led_php_a8834d8f177b8ab098b107020de280ef2"><div class="ttname"><a href="class_n_r_e_1_1_micro_1_1_led.php#a8834d8f177b8ab098b107020de280ef2">NRE::Micro::Led::turnOn</a></div><div class="ttdeci">void turnOn() const </div><div class="ttdef"><b>Definition:</b> NRE_LedInl.hpp:25</div></div>
<div class="ttc" id="namespace_n_r_e_php"><div class="ttname"><a href="namespace_n_r_e.php">NRE</a></div><div class="ttdoc">The NearlyRealEngine&amp;#39;s global namespace. </div><div class="ttdef"><b>Definition:</b> NRE_AbstractModule.cpp:12</div></div>
<div class="ttc" id="class_n_r_e_1_1_micro_1_1_led_php_a84e8281436fa31ffbb4eb39ef6aaba4b"><div class="ttname"><a href="class_n_r_e_1_1_micro_1_1_led.php#a84e8281436fa31ffbb4eb39ef6aaba4b">NRE::Micro::Led::setColor</a></div><div class="ttdeci">void setColor(Color const &amp;color)</div><div class="ttdef"><b>Definition:</b> NRE_LedInl.hpp:33</div></div>
<div class="ttc" id="class_n_r_e_1_1_micro_1_1_led_controller_php"><div class="ttname"><a href="class_n_r_e_1_1_micro_1_1_led_controller.php">NRE::Micro::LedController</a></div><div class="ttdoc">Manage access to a led component. </div><div class="ttdef"><b>Definition:</b> NRE_LedController.hpp:125</div></div>
<div class="ttc" id="class_n_r_e_1_1_micro_1_1_led_php_a144cb7e189a4850cf3f5c045c45d5fab"><div class="ttname"><a href="class_n_r_e_1_1_micro_1_1_led.php#a144cb7e189a4850cf3f5c045c45d5fab">NRE::Micro::Led::getColor</a></div><div class="ttdeci">CompressedColor getColor() const </div><div class="ttdef"><b>Definition:</b> NRE_LedInl.hpp:29</div></div>
<div class="ttc" id="class_n_r_e_1_1_micro_1_1_led_controller_php_a0b8a39b1a9e132de0f7c2fc5127e8ab0"><div class="ttname"><a href="class_n_r_e_1_1_micro_1_1_led_controller.php#a0b8a39b1a9e132de0f7c2fc5127e8ab0">NRE::Micro::LedController::turnOn</a></div><div class="ttdeci">void turnOn()</div><div class="ttdef"><b>Definition:</b> NRE_LedControllerInl.hpp:62</div></div>
</div><!-- fragment --></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
