<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Micro: /mnt/c/Users/abell/Documents/GitHub/NRE-Micro/src/Core/NRE_CoreInl.hpp Source File</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="files.php"><span>File&#160;List</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_68267d1309a1af8e8297ef4c3efbcdba.php">src</a></li><li class="navelem"><a class="el" href="dir_a2f0e5642e47e7ed59fe0f0829eafb5f.php">Core</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE_CoreInl.hpp</div>  </div>
</div><!--header-->
<div class="contents">
<a href="_n_r_e___core_inl_8hpp.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;</div><div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;    <span class="keyword">namespace </span><a class="code" href="namespace_n_r_e.php">NRE</a> {</div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;        <span class="keyword">namespace </span><a class="code" href="namespace_micro.php">Micro</a> {</div><div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;</div><div class="line"><a name="l00013"></a><span class="lineno">   13</span>&#160;            <span class="keyword">template</span> &lt;<span class="keyword">class</span> SubModule&gt;</div><div class="line"><a name="l00014"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#aea38fe1e1b792700bc032cb8471ab028">   14</a></span>&#160;            <span class="keyword">inline</span> <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#aea38fe1e1b792700bc032cb8471ab028">MicroManager::addModule</a>(SubModule* module) {</div><div class="line"><a name="l00015"></a><span class="lineno">   15</span>&#160;                assert(modules.size() == SubModule::getId());</div><div class="line"><a name="l00016"></a><span class="lineno">   16</span>&#160;                modules.push_back(module);</div><div class="line"><a name="l00017"></a><span class="lineno">   17</span>&#160;            }</div><div class="line"><a name="l00018"></a><span class="lineno">   18</span>&#160;</div><div class="line"><a name="l00019"></a><span class="lineno">   19</span>&#160;            <span class="keyword">template</span> &lt;<span class="keyword">class</span> SubModule&gt;</div><div class="line"><a name="l00020"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#abae5088c23e05992e055aaa14a332ab9">   20</a></span>&#160;            <span class="keyword">inline</span> SubModule&amp; <a class="code" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#abae5088c23e05992e055aaa14a332ab9">MicroManager::getModule</a>() {</div><div class="line"><a name="l00021"></a><span class="lineno">   21</span>&#160;                <span class="keywordflow">return</span> *(static_cast &lt;SubModule*&gt; (modules[SubModule::getId()]));</div><div class="line"><a name="l00022"></a><span class="lineno">   22</span>&#160;            }</div><div class="line"><a name="l00023"></a><span class="lineno">   23</span>&#160;</div><div class="line"><a name="l00024"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#a39f9b0ec9a1d09b092fb833cf41c32cd">   24</a></span>&#160;            <span class="keyword">inline</span> <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#a39f9b0ec9a1d09b092fb833cf41c32cd">MicroManager::setupModules</a>() {</div><div class="line"><a name="l00025"></a><span class="lineno">   25</span>&#160;                <span class="keywordflow">for</span> (<a class="code" href="class_n_r_e_1_1_micro_1_1_abstract_module.php">AbstractModule</a>* module : modules) {</div><div class="line"><a name="l00026"></a><span class="lineno">   26</span>&#160;                    module-&gt;setup();</div><div class="line"><a name="l00027"></a><span class="lineno">   27</span>&#160;                }</div><div class="line"><a name="l00028"></a><span class="lineno">   28</span>&#160;            }</div><div class="line"><a name="l00029"></a><span class="lineno">   29</span>&#160;</div><div class="line"><a name="l00030"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#aa1fce2c43a932cce99e74e8423fe8099">   30</a></span>&#160;            <span class="keyword">inline</span> <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#aa1fce2c43a932cce99e74e8423fe8099">MicroManager::loopModules</a>() {</div><div class="line"><a name="l00031"></a><span class="lineno">   31</span>&#160;                <span class="keywordflow">for</span> (<a class="code" href="class_n_r_e_1_1_micro_1_1_abstract_module.php">AbstractModule</a>* module : modules) {</div><div class="line"><a name="l00032"></a><span class="lineno">   32</span>&#160;                    module-&gt;loop();</div><div class="line"><a name="l00033"></a><span class="lineno">   33</span>&#160;                }</div><div class="line"><a name="l00034"></a><span class="lineno">   34</span>&#160;            }</div><div class="line"><a name="l00035"></a><span class="lineno">   35</span>&#160;</div><div class="line"><a name="l00036"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#a0e8afcf29c4af96d8b26172b9c266879">   36</a></span>&#160;            <span class="keyword">inline</span> <a class="code" href="class_n_r_e_1_1_micro_1_1_micro_manager.php">MicroManager</a>&amp; <a class="code" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#a0e8afcf29c4af96d8b26172b9c266879">MicroManager::get</a>() {</div><div class="line"><a name="l00037"></a><span class="lineno">   37</span>&#160;                <span class="keyword">static</span> <a class="code" href="class_n_r_e_1_1_micro_1_1_micro_manager.php">MicroManager</a> instance;</div><div class="line"><a name="l00038"></a><span class="lineno">   38</span>&#160;                <span class="keywordflow">return</span> instance;</div><div class="line"><a name="l00039"></a><span class="lineno">   39</span>&#160;            }</div><div class="line"><a name="l00040"></a><span class="lineno">   40</span>&#160;</div><div class="line"><a name="l00041"></a><span class="lineno">   41</span>&#160;            <span class="keyword">template</span> &lt;<span class="keyword">class</span> SubModule&gt;</div><div class="line"><a name="l00042"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#a30db23a789e19edbe1547c1f3b38f85c">   42</a></span>&#160;            <span class="keyword">inline</span> <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#a30db23a789e19edbe1547c1f3b38f85c">MicroManager::add</a>(SubModule* module) {</div><div class="line"><a name="l00043"></a><span class="lineno">   43</span>&#160;                <a class="code" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#a0e8afcf29c4af96d8b26172b9c266879">MicroManager::get</a>().<a class="code" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#aea38fe1e1b792700bc032cb8471ab028">addModule</a>(module);</div><div class="line"><a name="l00044"></a><span class="lineno">   44</span>&#160;            }</div><div class="line"><a name="l00045"></a><span class="lineno">   45</span>&#160;</div><div class="line"><a name="l00046"></a><span class="lineno">   46</span>&#160;            <span class="keyword">template</span> &lt;<span class="keyword">class</span> SubModule&gt;</div><div class="line"><a name="l00047"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#a5810aa873a9ba19a2f0737b383cedb33">   47</a></span>&#160;            <span class="keyword">inline</span> SubModule&amp; <a class="code" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#a0e8afcf29c4af96d8b26172b9c266879">MicroManager::get</a>() {</div><div class="line"><a name="l00048"></a><span class="lineno">   48</span>&#160;                <span class="keywordflow">return</span> <a class="code" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#a0e8afcf29c4af96d8b26172b9c266879">MicroManager::get</a>().<a class="code" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#abae5088c23e05992e055aaa14a332ab9">getModule</a>&lt;SubModule&gt;();</div><div class="line"><a name="l00049"></a><span class="lineno">   49</span>&#160;            }</div><div class="line"><a name="l00050"></a><span class="lineno">   50</span>&#160;</div><div class="line"><a name="l00051"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#a8d9a10df1225539a2dcde55dd7c6ed32">   51</a></span>&#160;            <span class="keyword">inline</span> <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#a8d9a10df1225539a2dcde55dd7c6ed32">MicroManager::setup</a>() {</div><div class="line"><a name="l00052"></a><span class="lineno">   52</span>&#160;                <a class="code" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#a0e8afcf29c4af96d8b26172b9c266879">MicroManager::get</a>().<a class="code" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#a39f9b0ec9a1d09b092fb833cf41c32cd">setupModules</a>();</div><div class="line"><a name="l00053"></a><span class="lineno">   53</span>&#160;            }</div><div class="line"><a name="l00054"></a><span class="lineno">   54</span>&#160;</div><div class="line"><a name="l00055"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#ae353a1ea48369af4c9783977b2b9995a">   55</a></span>&#160;            <span class="keyword">inline</span> <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#ae353a1ea48369af4c9783977b2b9995a">MicroManager::loop</a>() {</div><div class="line"><a name="l00056"></a><span class="lineno">   56</span>&#160;                <a class="code" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#a0e8afcf29c4af96d8b26172b9c266879">MicroManager::get</a>().<a class="code" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#aa1fce2c43a932cce99e74e8423fe8099">loopModules</a>();</div><div class="line"><a name="l00057"></a><span class="lineno">   57</span>&#160;            }</div><div class="line"><a name="l00058"></a><span class="lineno">   58</span>&#160;</div><div class="line"><a name="l00059"></a><span class="lineno">   59</span>&#160;        }</div><div class="line"><a name="l00060"></a><span class="lineno">   60</span>&#160;    }</div><div class="ttc" id="class_n_r_e_1_1_micro_1_1_micro_manager_php_abae5088c23e05992e055aaa14a332ab9"><div class="ttname"><a href="class_n_r_e_1_1_micro_1_1_micro_manager.php#abae5088c23e05992e055aaa14a332ab9">NRE::Micro::MicroManager::getModule</a></div><div class="ttdeci">SubModule &amp; getModule()</div><div class="ttdef"><b>Definition:</b> NRE_CoreInl.hpp:20</div></div>
<div class="ttc" id="class_n_r_e_1_1_micro_1_1_micro_manager_php_a39f9b0ec9a1d09b092fb833cf41c32cd"><div class="ttname"><a href="class_n_r_e_1_1_micro_1_1_micro_manager.php#a39f9b0ec9a1d09b092fb833cf41c32cd">NRE::Micro::MicroManager::setupModules</a></div><div class="ttdeci">void setupModules()</div><div class="ttdef"><b>Definition:</b> NRE_CoreInl.hpp:24</div></div>
<div class="ttc" id="namespace_micro_php"><div class="ttname"><a href="namespace_micro.php">Micro</a></div><div class="ttdoc">Micro&amp;#39;s API. </div></div>
<div class="ttc" id="class_n_r_e_1_1_micro_1_1_micro_manager_php_a8d9a10df1225539a2dcde55dd7c6ed32"><div class="ttname"><a href="class_n_r_e_1_1_micro_1_1_micro_manager.php#a8d9a10df1225539a2dcde55dd7c6ed32">NRE::Micro::MicroManager::setup</a></div><div class="ttdeci">static void setup()</div><div class="ttdef"><b>Definition:</b> NRE_CoreInl.hpp:51</div></div>
<div class="ttc" id="class_n_r_e_1_1_micro_1_1_micro_manager_php_aea38fe1e1b792700bc032cb8471ab028"><div class="ttname"><a href="class_n_r_e_1_1_micro_1_1_micro_manager.php#aea38fe1e1b792700bc032cb8471ab028">NRE::Micro::MicroManager::addModule</a></div><div class="ttdeci">void addModule(SubModule *module)</div><div class="ttdef"><b>Definition:</b> NRE_CoreInl.hpp:14</div></div>
<div class="ttc" id="class_n_r_e_1_1_micro_1_1_abstract_module_php"><div class="ttname"><a href="class_n_r_e_1_1_micro_1_1_abstract_module.php">NRE::Micro::AbstractModule</a></div><div class="ttdoc">Represent an abstract module used to active a certain part of the framework. </div><div class="ttdef"><b>Definition:</b> NRE_AbstractModule.hpp:29</div></div>
<div class="ttc" id="class_n_r_e_1_1_micro_1_1_micro_manager_php_a30db23a789e19edbe1547c1f3b38f85c"><div class="ttname"><a href="class_n_r_e_1_1_micro_1_1_micro_manager.php#a30db23a789e19edbe1547c1f3b38f85c">NRE::Micro::MicroManager::add</a></div><div class="ttdeci">static void add(SubModule *module)</div><div class="ttdef"><b>Definition:</b> NRE_CoreInl.hpp:42</div></div>
<div class="ttc" id="namespace_n_r_e_php"><div class="ttname"><a href="namespace_n_r_e.php">NRE</a></div><div class="ttdoc">The NearlyRealEngine&amp;#39;s global namespace. </div><div class="ttdef"><b>Definition:</b> NRE_AbstractModule.cpp:12</div></div>
<div class="ttc" id="class_n_r_e_1_1_micro_1_1_micro_manager_php"><div class="ttname"><a href="class_n_r_e_1_1_micro_1_1_micro_manager.php">NRE::Micro::MicroManager</a></div><div class="ttdoc">Manage all modules in the framework, allowing the user simple utilisation of ESP8266 library and func...</div><div class="ttdef"><b>Definition:</b> NRE_Core.hpp:36</div></div>
<div class="ttc" id="class_n_r_e_1_1_micro_1_1_micro_manager_php_aa1fce2c43a932cce99e74e8423fe8099"><div class="ttname"><a href="class_n_r_e_1_1_micro_1_1_micro_manager.php#aa1fce2c43a932cce99e74e8423fe8099">NRE::Micro::MicroManager::loopModules</a></div><div class="ttdeci">void loopModules()</div><div class="ttdef"><b>Definition:</b> NRE_CoreInl.hpp:30</div></div>
<div class="ttc" id="class_n_r_e_1_1_micro_1_1_micro_manager_php_ae353a1ea48369af4c9783977b2b9995a"><div class="ttname"><a href="class_n_r_e_1_1_micro_1_1_micro_manager.php#ae353a1ea48369af4c9783977b2b9995a">NRE::Micro::MicroManager::loop</a></div><div class="ttdeci">static void loop()</div><div class="ttdef"><b>Definition:</b> NRE_CoreInl.hpp:55</div></div>
<div class="ttc" id="class_n_r_e_1_1_micro_1_1_micro_manager_php_a0e8afcf29c4af96d8b26172b9c266879"><div class="ttname"><a href="class_n_r_e_1_1_micro_1_1_micro_manager.php#a0e8afcf29c4af96d8b26172b9c266879">NRE::Micro::MicroManager::get</a></div><div class="ttdeci">static MicroManager &amp; get()</div><div class="ttdef"><b>Definition:</b> NRE_CoreInl.hpp:36</div></div>
</div><!-- fragment --></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
