<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Micro: /mnt/c/Users/abell/Documents/GitHub/NRE-Micro/src/LED/Manager/NRE_LedManagerInl.hpp Source File</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="files.php"><span>File&#160;List</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_68267d1309a1af8e8297ef4c3efbcdba.php">src</a></li><li class="navelem"><a class="el" href="dir_6b864641f3cab9a7d09fa51df47d12f6.php">LED</a></li><li class="navelem"><a class="el" href="dir_a164b43b90bb7e8c56f5aba4d3c7529c.php">Manager</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE_LedManagerInl.hpp</div>  </div>
</div><!--header-->
<div class="contents">
<a href="_n_r_e___led_manager_inl_8hpp.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;</div><div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;    <span class="keyword">namespace </span><a class="code" href="namespace_n_r_e.php">NRE</a> {</div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;        <span class="keyword">namespace </span><a class="code" href="namespace_micro.php">Micro</a> {</div><div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;</div><div class="line"><a name="l00013"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_micro_1_1_led_manager.php#aa13e06d999087f6f193f4804419d86a0">   13</a></span>&#160;            <span class="keyword">inline</span> <a class="code" href="class_n_r_e_1_1_micro_1_1_led_manager.php#aa13e06d999087f6f193f4804419d86a0">LedManager::~LedManager</a>() {</div><div class="line"><a name="l00014"></a><span class="lineno">   14</span>&#160;                <span class="keywordflow">for</span> (<a class="code" href="class_n_r_e_1_1_micro_1_1_led_controller.php">LedController</a>* controller : controllers) {</div><div class="line"><a name="l00015"></a><span class="lineno">   15</span>&#160;                    <span class="keyword">delete</span> controller;</div><div class="line"><a name="l00016"></a><span class="lineno">   16</span>&#160;                    controller = <span class="keyword">nullptr</span>;</div><div class="line"><a name="l00017"></a><span class="lineno">   17</span>&#160;                }</div><div class="line"><a name="l00018"></a><span class="lineno">   18</span>&#160;            }</div><div class="line"><a name="l00019"></a><span class="lineno">   19</span>&#160;</div><div class="line"><a name="l00020"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_micro_1_1_led_manager.php#aa64ef572a79d594e67843ee27bf74b46">   20</a></span>&#160;            <span class="keyword">inline</span> <a class="code" href="class_n_r_e_1_1_micro_1_1_led_controller.php">LedController</a>&amp; <a class="code" href="class_n_r_e_1_1_micro_1_1_led_manager.php#aa64ef572a79d594e67843ee27bf74b46">LedManager::getController</a>(<span class="keywordtype">unsigned</span> <span class="keywordtype">char</span> <span class="keywordtype">id</span>) {</div><div class="line"><a name="l00021"></a><span class="lineno">   21</span>&#160;                <span class="keywordflow">return</span> *(controllers[id]);</div><div class="line"><a name="l00022"></a><span class="lineno">   22</span>&#160;            }</div><div class="line"><a name="l00023"></a><span class="lineno">   23</span>&#160;</div><div class="line"><a name="l00024"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_micro_1_1_led_manager.php#aa778378bc85b3894103d1eabb5a80cd3">   24</a></span>&#160;            <span class="keyword">inline</span> <span class="keywordtype">unsigned</span> <span class="keywordtype">char</span> <a class="code" href="class_n_r_e_1_1_micro_1_1_led_manager.php#aa778378bc85b3894103d1eabb5a80cd3">LedManager::addController</a>(LedId nb, Pin pin, neoPixelType type) {</div><div class="line"><a name="l00025"></a><span class="lineno">   25</span>&#160;                <span class="keywordtype">int</span> <span class="keywordtype">id</span> = controllers.size();</div><div class="line"><a name="l00026"></a><span class="lineno">   26</span>&#160;                controllers.push_back(<span class="keyword">new</span> <a class="code" href="class_n_r_e_1_1_micro_1_1_led_controller.php">LedController</a>(nb, pin, type));</div><div class="line"><a name="l00027"></a><span class="lineno">   27</span>&#160;                <span class="keywordflow">return</span> id;</div><div class="line"><a name="l00028"></a><span class="lineno">   28</span>&#160;            }</div><div class="line"><a name="l00029"></a><span class="lineno">   29</span>&#160;</div><div class="line"><a name="l00030"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_micro_1_1_led_manager.php#a72b0073aef8f0e38e59fd141d719acc2">   30</a></span>&#160;            <span class="keyword">inline</span> <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_micro_1_1_led_manager.php#a72b0073aef8f0e38e59fd141d719acc2">LedManager::setup</a>() {</div><div class="line"><a name="l00031"></a><span class="lineno">   31</span>&#160;                <span class="keywordflow">for</span> (<a class="code" href="class_n_r_e_1_1_micro_1_1_led_controller.php">LedController</a>* controller : controllers) {</div><div class="line"><a name="l00032"></a><span class="lineno">   32</span>&#160;                    controller-&gt;setup();</div><div class="line"><a name="l00033"></a><span class="lineno">   33</span>&#160;                }</div><div class="line"><a name="l00034"></a><span class="lineno">   34</span>&#160;            }</div><div class="line"><a name="l00035"></a><span class="lineno">   35</span>&#160;</div><div class="line"><a name="l00036"></a><span class="lineno">   36</span>&#160;        }</div><div class="line"><a name="l00037"></a><span class="lineno">   37</span>&#160;    }</div><div class="ttc" id="class_n_r_e_1_1_micro_1_1_led_manager_php_aa64ef572a79d594e67843ee27bf74b46"><div class="ttname"><a href="class_n_r_e_1_1_micro_1_1_led_manager.php#aa64ef572a79d594e67843ee27bf74b46">NRE::Micro::LedManager::getController</a></div><div class="ttdeci">LedController &amp; getController(unsigned char id)</div><div class="ttdef"><b>Definition:</b> NRE_LedManagerInl.hpp:20</div></div>
<div class="ttc" id="namespace_micro_php"><div class="ttname"><a href="namespace_micro.php">Micro</a></div><div class="ttdoc">Micro&amp;#39;s API. </div></div>
<div class="ttc" id="class_n_r_e_1_1_micro_1_1_led_manager_php_aa13e06d999087f6f193f4804419d86a0"><div class="ttname"><a href="class_n_r_e_1_1_micro_1_1_led_manager.php#aa13e06d999087f6f193f4804419d86a0">NRE::Micro::LedManager::~LedManager</a></div><div class="ttdeci">~LedManager()</div><div class="ttdef"><b>Definition:</b> NRE_LedManagerInl.hpp:13</div></div>
<div class="ttc" id="class_n_r_e_1_1_micro_1_1_led_manager_php_aa778378bc85b3894103d1eabb5a80cd3"><div class="ttname"><a href="class_n_r_e_1_1_micro_1_1_led_manager.php#aa778378bc85b3894103d1eabb5a80cd3">NRE::Micro::LedManager::addController</a></div><div class="ttdeci">unsigned char addController(LedId nb, Pin pin, neoPixelType type=NEO_GRB+NEO_KHZ800)</div><div class="ttdef"><b>Definition:</b> NRE_LedManagerInl.hpp:24</div></div>
<div class="ttc" id="class_n_r_e_1_1_micro_1_1_led_manager_php_a72b0073aef8f0e38e59fd141d719acc2"><div class="ttname"><a href="class_n_r_e_1_1_micro_1_1_led_manager.php#a72b0073aef8f0e38e59fd141d719acc2">NRE::Micro::LedManager::setup</a></div><div class="ttdeci">void setup() override</div><div class="ttdef"><b>Definition:</b> NRE_LedManagerInl.hpp:30</div></div>
<div class="ttc" id="namespace_n_r_e_php"><div class="ttname"><a href="namespace_n_r_e.php">NRE</a></div><div class="ttdoc">The NearlyRealEngine&amp;#39;s global namespace. </div><div class="ttdef"><b>Definition:</b> NRE_AbstractModule.cpp:12</div></div>
<div class="ttc" id="class_n_r_e_1_1_micro_1_1_led_controller_php"><div class="ttname"><a href="class_n_r_e_1_1_micro_1_1_led_controller.php">NRE::Micro::LedController</a></div><div class="ttdoc">Manage access to a led component. </div><div class="ttdef"><b>Definition:</b> NRE_LedController.hpp:125</div></div>
</div><!-- fragment --></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
