<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Micro: NRE::Micro::MicroManager Class Reference</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>Micro</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php">MicroManager</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pub-static-methods">Static Public Member Functions</a> &#124;
<a href="class_n_r_e_1_1_micro_1_1_micro_manager-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">NRE::Micro::MicroManager Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>Manage all modules in the framework, allowing the user simple utilisation of ESP8266 library and functionnality.  
 <a href="class_n_r_e_1_1_micro_1_1_micro_manager.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="_core_2_n_r_e___core_8hpp_source.php">NRE_Core.hpp</a>&gt;</code></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a69fb44d8d24a58ed84866f5be95ee6be"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#a69fb44d8d24a58ed84866f5be95ee6be">MicroManager</a> ()=default</td></tr>
<tr class="separator:a69fb44d8d24a58ed84866f5be95ee6be"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aed7cb06d6e864e410f87cd45047af556"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#aed7cb06d6e864e410f87cd45047af556">MicroManager</a> (<a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php">MicroManager</a> const &amp;mng)=delete</td></tr>
<tr class="separator:aed7cb06d6e864e410f87cd45047af556"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac48667370b771b06f12ae3b7a9f1609f"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#ac48667370b771b06f12ae3b7a9f1609f">MicroManager</a> (<a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php">MicroManager</a> &amp;&amp;mng)=delete</td></tr>
<tr class="separator:ac48667370b771b06f12ae3b7a9f1609f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a321ee576959f42775fbde9d4a092f7e2"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#a321ee576959f42775fbde9d4a092f7e2">~MicroManager</a> ()=default</td></tr>
<tr class="separator:a321ee576959f42775fbde9d4a092f7e2"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aea38fe1e1b792700bc032cb8471ab028"><td class="memTemplParams" colspan="2">template&lt;class SubModule &gt; </td></tr>
<tr class="memitem:aea38fe1e1b792700bc032cb8471ab028"><td class="memTemplItemLeft" align="right" valign="top">void&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#aea38fe1e1b792700bc032cb8471ab028">addModule</a> (SubModule *module)</td></tr>
<tr class="separator:aea38fe1e1b792700bc032cb8471ab028"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:abae5088c23e05992e055aaa14a332ab9"><td class="memTemplParams" colspan="2">template&lt;class SubModule &gt; </td></tr>
<tr class="memitem:abae5088c23e05992e055aaa14a332ab9"><td class="memTemplItemLeft" align="right" valign="top">SubModule &amp;&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#abae5088c23e05992e055aaa14a332ab9">getModule</a> ()</td></tr>
<tr class="separator:abae5088c23e05992e055aaa14a332ab9"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a39f9b0ec9a1d09b092fb833cf41c32cd"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#a39f9b0ec9a1d09b092fb833cf41c32cd">setupModules</a> ()</td></tr>
<tr class="separator:a39f9b0ec9a1d09b092fb833cf41c32cd"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa1fce2c43a932cce99e74e8423fe8099"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#aa1fce2c43a932cce99e74e8423fe8099">loopModules</a> ()</td></tr>
<tr class="separator:aa1fce2c43a932cce99e74e8423fe8099"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a392856201b2ab654762f8a6bfa4fa0d8"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php">MicroManager</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#a392856201b2ab654762f8a6bfa4fa0d8">operator=</a> (<a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php">MicroManager</a> const &amp;mng)=delete</td></tr>
<tr class="separator:a392856201b2ab654762f8a6bfa4fa0d8"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a04b10ab9a31b149214864888cfec6617"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php">MicroManager</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#a04b10ab9a31b149214864888cfec6617">operator=</a> (<a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php">MicroManager</a> &amp;&amp;mng)=delete</td></tr>
<tr class="separator:a04b10ab9a31b149214864888cfec6617"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-static-methods"></a>
Static Public Member Functions</h2></td></tr>
<tr class="memitem:a0e8afcf29c4af96d8b26172b9c266879"><td class="memItemLeft" align="right" valign="top">static <a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php">MicroManager</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#a0e8afcf29c4af96d8b26172b9c266879">get</a> ()</td></tr>
<tr class="separator:a0e8afcf29c4af96d8b26172b9c266879"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a30db23a789e19edbe1547c1f3b38f85c"><td class="memTemplParams" colspan="2">template&lt;class SubModule &gt; </td></tr>
<tr class="memitem:a30db23a789e19edbe1547c1f3b38f85c"><td class="memTemplItemLeft" align="right" valign="top">static void&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#a30db23a789e19edbe1547c1f3b38f85c">add</a> (SubModule *module)</td></tr>
<tr class="separator:a30db23a789e19edbe1547c1f3b38f85c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a5810aa873a9ba19a2f0737b383cedb33"><td class="memTemplParams" colspan="2">template&lt;class SubModule &gt; </td></tr>
<tr class="memitem:a5810aa873a9ba19a2f0737b383cedb33"><td class="memTemplItemLeft" align="right" valign="top">static SubModule &amp;&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#a5810aa873a9ba19a2f0737b383cedb33">get</a> ()</td></tr>
<tr class="separator:a5810aa873a9ba19a2f0737b383cedb33"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8d9a10df1225539a2dcde55dd7c6ed32"><td class="memItemLeft" align="right" valign="top">static void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#a8d9a10df1225539a2dcde55dd7c6ed32">setup</a> ()</td></tr>
<tr class="separator:a8d9a10df1225539a2dcde55dd7c6ed32"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae353a1ea48369af4c9783977b2b9995a"><td class="memItemLeft" align="right" valign="top">static void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#ae353a1ea48369af4c9783977b2b9995a">loop</a> ()</td></tr>
<tr class="separator:ae353a1ea48369af4c9783977b2b9995a"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>Manage all modules in the framework, allowing the user simple utilisation of ESP8266 library and functionnality. </p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="a69fb44d8d24a58ed84866f5be95ee6be"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Micro::MicroManager::MicroManager </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Construct the micro manager </p>

</div>
</div>
<a class="anchor" id="aed7cb06d6e864e410f87cd45047af556"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Micro::MicroManager::MicroManager </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php">MicroManager</a> const &amp;&#160;</td>
          <td class="paramname"><em>mng</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy forbidden </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">mng</td><td>the manager to copy </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="ac48667370b771b06f12ae3b7a9f1609f"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Micro::MicroManager::MicroManager </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php">MicroManager</a> &amp;&amp;&#160;</td>
          <td class="paramname"><em>mng</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move forbidden </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">mng</td><td>the manager to move </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a321ee576959f42775fbde9d4a092f7e2"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Micro::MicroManager::~MicroManager </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php" title="Manage all modules in the framework, allowing the user simple utilisation of ESP8266 library and func...">MicroManager</a> Deconstructor </p>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="a30db23a789e19edbe1547c1f3b38f85c"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class SubModule &gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Micro::MicroManager::add </td>
          <td>(</td>
          <td class="paramtype">SubModule *&#160;</td>
          <td class="paramname"><em>module</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span><span class="mlabel">static</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Add a sub module to the core </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">module</td><td>the module to add </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="aea38fe1e1b792700bc032cb8471ab028"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class SubModule &gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Micro::MicroManager::addModule </td>
          <td>(</td>
          <td class="paramtype">SubModule *&#160;</td>
          <td class="paramname"><em>module</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Add a sub module to the core </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">module</td><td>the module to add </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a0e8afcf29c4af96d8b26172b9c266879"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php">MicroManager</a> &amp; NRE::Micro::MicroManager::get </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span><span class="mlabel">static</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the micro manager instance </dd></dl>

</div>
</div>
<a class="anchor" id="a5810aa873a9ba19a2f0737b383cedb33"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class SubModule &gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">SubModule &amp; NRE::Micro::MicroManager::get </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span><span class="mlabel">static</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>a manager module </dd></dl>

</div>
</div>
<a class="anchor" id="abae5088c23e05992e055aaa14a332ab9"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class SubModule &gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">SubModule &amp; NRE::Micro::MicroManager::getModule </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>a manager module </dd></dl>

</div>
</div>
<a class="anchor" id="ae353a1ea48369af4c9783977b2b9995a"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Micro::MicroManager::loop </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span><span class="mlabel">static</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Handle the loop for all modules </p>

</div>
</div>
<a class="anchor" id="aa1fce2c43a932cce99e74e8423fe8099"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Micro::MicroManager::loopModules </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Handle the loop for all modules </p>

</div>
</div>
<a class="anchor" id="a392856201b2ab654762f8a6bfa4fa0d8"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php">MicroManager</a>&amp; NRE::Micro::MicroManager::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php">MicroManager</a> const &amp;&#160;</td>
          <td class="paramname"><em>mng</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy assign forbidden </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">mng</td><td>the manager to copy </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="a04b10ab9a31b149214864888cfec6617"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php">MicroManager</a>&amp; NRE::Micro::MicroManager::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php">MicroManager</a> &amp;&amp;&#160;</td>
          <td class="paramname"><em>mng</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move assign forbidden </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">mng</td><td>the manager to move </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="a8d9a10df1225539a2dcde55dd7c6ed32"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Micro::MicroManager::setup </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span><span class="mlabel">static</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Setup all modules </p>

</div>
</div>
<a class="anchor" id="a39f9b0ec9a1d09b092fb833cf41c32cd"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Micro::MicroManager::setupModules </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Setup all modules </p>

</div>
</div>
<hr/>The documentation for this class was generated from the following files:<ul>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-Micro/src/Core/<a class="el" href="_core_2_n_r_e___core_8hpp_source.php">NRE_Core.hpp</a></li>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-Micro/src/Core/<a class="el" href="_n_r_e___core_inl_8hpp_source.php">NRE_CoreInl.hpp</a></li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
