<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Micro: NRE::Micro::Color Class Reference</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>Micro</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php">Color</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pub-static-methods">Static Public Member Functions</a> &#124;
<a href="class_n_r_e_1_1_micro_1_1_color-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">NRE::Micro::Color Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>Represent a led <a class="el" href="class_n_r_e_1_1_micro_1_1_color.php" title="Represent a led Color. ">Color</a>.  
 <a href="class_n_r_e_1_1_micro_1_1_color.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="_n_r_e___color_8hpp_source.php">NRE_Color.hpp</a>&gt;</code></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a4e5a2d8b901b97ba413a67cc5b43b597"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php#a4e5a2d8b901b97ba413a67cc5b43b597">Color</a> ()=default</td></tr>
<tr class="separator:a4e5a2d8b901b97ba413a67cc5b43b597"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac4755c79a12aa581d38c95d35aebd8ce"><td class="memItemLeft" align="right" valign="top">constexpr&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php#ac4755c79a12aa581d38c95d35aebd8ce">Color</a> (ColorChannel red, ColorChannel green, ColorChannel blue)</td></tr>
<tr class="separator:ac4755c79a12aa581d38c95d35aebd8ce"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aff5a13a11e5ed0b490be89a320475dfe"><td class="memItemLeft" align="right" valign="top">constexpr&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php#aff5a13a11e5ed0b490be89a320475dfe">Color</a> (CompressedColor color)</td></tr>
<tr class="separator:aff5a13a11e5ed0b490be89a320475dfe"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9b85cf58034515554496ee4153065169"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php#a9b85cf58034515554496ee4153065169">Color</a> (<a class="el" href="class_n_r_e_1_1_micro_1_1_color.php">Color</a> const &amp;c)=default</td></tr>
<tr class="separator:a9b85cf58034515554496ee4153065169"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad4e3c5aca1fd3a4426d1b222ba3b83c3"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php#ad4e3c5aca1fd3a4426d1b222ba3b83c3">Color</a> (<a class="el" href="class_n_r_e_1_1_micro_1_1_color.php">Color</a> &amp;&amp;c)=default</td></tr>
<tr class="separator:ad4e3c5aca1fd3a4426d1b222ba3b83c3"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a990af7dcc72d09ca41de6f8d1277625b"><td class="memItemLeft" align="right" valign="top">ColorChannel&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php#a990af7dcc72d09ca41de6f8d1277625b">getR</a> () const </td></tr>
<tr class="separator:a990af7dcc72d09ca41de6f8d1277625b"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a12f1cee974aad505f24f8287f8a970cf"><td class="memItemLeft" align="right" valign="top">ColorChannel&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php#a12f1cee974aad505f24f8287f8a970cf">getG</a> () const </td></tr>
<tr class="separator:a12f1cee974aad505f24f8287f8a970cf"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3e3a8e355ee733ac09ae1f10db9b57d0"><td class="memItemLeft" align="right" valign="top">ColorChannel&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php#a3e3a8e355ee733ac09ae1f10db9b57d0">getB</a> () const </td></tr>
<tr class="separator:a3e3a8e355ee733ac09ae1f10db9b57d0"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a724e75202b5bdfc0b64e5c1b0d9a0e9f"><td class="memItemLeft" align="right" valign="top">constexpr CompressedColor&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php#a724e75202b5bdfc0b64e5c1b0d9a0e9f">getColor</a> () const </td></tr>
<tr class="separator:a724e75202b5bdfc0b64e5c1b0d9a0e9f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a75ca29d00bb4353423ed452913ebe3f5"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php#a75ca29d00bb4353423ed452913ebe3f5">setR</a> (ColorChannel red)</td></tr>
<tr class="separator:a75ca29d00bb4353423ed452913ebe3f5"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a1089d94cf65cff8dac8da2da6af8bcd0"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php#a1089d94cf65cff8dac8da2da6af8bcd0">setG</a> (ColorChannel green)</td></tr>
<tr class="separator:a1089d94cf65cff8dac8da2da6af8bcd0"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aafcd2a06071ec32b4f6e7ac9a2d0d6a4"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php#aafcd2a06071ec32b4f6e7ac9a2d0d6a4">setB</a> (ColorChannel blue)</td></tr>
<tr class="separator:aafcd2a06071ec32b4f6e7ac9a2d0d6a4"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a81e0b2b65ecf8e672ba31f1691a3be75"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php">Color</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php#a81e0b2b65ecf8e672ba31f1691a3be75">operator=</a> (<a class="el" href="class_n_r_e_1_1_micro_1_1_color.php">Color</a> const &amp;c)=default</td></tr>
<tr class="separator:a81e0b2b65ecf8e672ba31f1691a3be75"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a54ebd96ab6544209832237765e7afc22"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php">Color</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php#a54ebd96ab6544209832237765e7afc22">operator=</a> (<a class="el" href="class_n_r_e_1_1_micro_1_1_color.php">Color</a> &amp;&amp;c)=default</td></tr>
<tr class="separator:a54ebd96ab6544209832237765e7afc22"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-static-methods"></a>
Static Public Member Functions</h2></td></tr>
<tr class="memitem:a866fa6ed8ce1aa378ba92a97e5c0d7f0"><td class="memItemLeft" align="right" valign="top">static constexpr ColorChannel&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php#a866fa6ed8ce1aa378ba92a97e5c0d7f0">extractR</a> (CompressedColor color)</td></tr>
<tr class="separator:a866fa6ed8ce1aa378ba92a97e5c0d7f0"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae6f843b4e3974141004b54fccca9978d"><td class="memItemLeft" align="right" valign="top">static constexpr ColorChannel&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php#ae6f843b4e3974141004b54fccca9978d">extractR</a> (<a class="el" href="class_n_r_e_1_1_micro_1_1_color.php">Color</a> const &amp;color)</td></tr>
<tr class="separator:ae6f843b4e3974141004b54fccca9978d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad83102ad4e6250d498e99a6ede2a5051"><td class="memItemLeft" align="right" valign="top">static constexpr ColorChannel&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php#ad83102ad4e6250d498e99a6ede2a5051">extractG</a> (CompressedColor color)</td></tr>
<tr class="separator:ad83102ad4e6250d498e99a6ede2a5051"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a84fe855a786f4f39d64eed3f874609b3"><td class="memItemLeft" align="right" valign="top">static constexpr ColorChannel&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php#a84fe855a786f4f39d64eed3f874609b3">extractG</a> (<a class="el" href="class_n_r_e_1_1_micro_1_1_color.php">Color</a> const &amp;color)</td></tr>
<tr class="separator:a84fe855a786f4f39d64eed3f874609b3"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a5912ab8577748c36a5896924ed326b8a"><td class="memItemLeft" align="right" valign="top">static constexpr ColorChannel&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php#a5912ab8577748c36a5896924ed326b8a">extractB</a> (CompressedColor color)</td></tr>
<tr class="separator:a5912ab8577748c36a5896924ed326b8a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a95b36171d189b73f635cad6eeb0bc8b4"><td class="memItemLeft" align="right" valign="top">static constexpr ColorChannel&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php#a95b36171d189b73f635cad6eeb0bc8b4">extractB</a> (<a class="el" href="class_n_r_e_1_1_micro_1_1_color.php">Color</a> const &amp;color)</td></tr>
<tr class="separator:a95b36171d189b73f635cad6eeb0bc8b4"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>Represent a led <a class="el" href="class_n_r_e_1_1_micro_1_1_color.php" title="Represent a led Color. ">Color</a>. </p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="a4e5a2d8b901b97ba413a67cc5b43b597"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Micro::Color::Color </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Default constructor </p>

</div>
</div>
<a class="anchor" id="ac4755c79a12aa581d38c95d35aebd8ce"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">constexpr NRE::Micro::Color::Color </td>
          <td>(</td>
          <td class="paramtype">ColorChannel&#160;</td>
          <td class="paramname"><em>red</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">ColorChannel&#160;</td>
          <td class="paramname"><em>green</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">ColorChannel&#160;</td>
          <td class="paramname"><em>blue</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Construct the color from all channel </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">red</td><td>the red value </td></tr>
    <tr><td class="paramname">green</td><td>the green value </td></tr>
    <tr><td class="paramname">blue</td><td>the blue value </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="aff5a13a11e5ed0b490be89a320475dfe"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">constexpr NRE::Micro::Color::Color </td>
          <td>(</td>
          <td class="paramtype">CompressedColor&#160;</td>
          <td class="paramname"><em>color</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Construct the color from a compressed one </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">color</td><td>the compressed color </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a9b85cf58034515554496ee4153065169"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Micro::Color::Color </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php">Color</a> const &amp;&#160;</td>
          <td class="paramname"><em>c</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy c into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">c</td><td>the color to copy </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="ad4e3c5aca1fd3a4426d1b222ba3b83c3"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Micro::Color::Color </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php">Color</a> &amp;&amp;&#160;</td>
          <td class="paramname"><em>c</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move c into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">c</td><td>the color to move </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="a5912ab8577748c36a5896924ed326b8a"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">static constexpr ColorChannel NRE::Micro::Color::extractB </td>
          <td>(</td>
          <td class="paramtype">CompressedColor&#160;</td>
          <td class="paramname"><em>color</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span><span class="mlabel">static</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Extract the blue channel from a color </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">color</td><td>the color to process </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the color blue channel </dd></dl>

</div>
</div>
<a class="anchor" id="a95b36171d189b73f635cad6eeb0bc8b4"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">static constexpr ColorChannel NRE::Micro::Color::extractB </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php">Color</a> const &amp;&#160;</td>
          <td class="paramname"><em>color</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span><span class="mlabel">static</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Extract the blue channel from a color </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">color</td><td>the color to process </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the color blue channel </dd></dl>

</div>
</div>
<a class="anchor" id="ad83102ad4e6250d498e99a6ede2a5051"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">static constexpr ColorChannel NRE::Micro::Color::extractG </td>
          <td>(</td>
          <td class="paramtype">CompressedColor&#160;</td>
          <td class="paramname"><em>color</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span><span class="mlabel">static</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Extract the green channel from a color </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">color</td><td>the color to process </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the color green channel </dd></dl>

</div>
</div>
<a class="anchor" id="a84fe855a786f4f39d64eed3f874609b3"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">static constexpr ColorChannel NRE::Micro::Color::extractG </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php">Color</a> const &amp;&#160;</td>
          <td class="paramname"><em>color</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span><span class="mlabel">static</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Extract the green channel from a color </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">color</td><td>the color to process </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the color green channel </dd></dl>

</div>
</div>
<a class="anchor" id="a866fa6ed8ce1aa378ba92a97e5c0d7f0"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">static constexpr ColorChannel NRE::Micro::Color::extractR </td>
          <td>(</td>
          <td class="paramtype">CompressedColor&#160;</td>
          <td class="paramname"><em>color</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span><span class="mlabel">static</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Extract the red channel from a color </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">color</td><td>the color to process </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the color red channel </dd></dl>

</div>
</div>
<a class="anchor" id="ae6f843b4e3974141004b54fccca9978d"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">static constexpr ColorChannel NRE::Micro::Color::extractR </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php">Color</a> const &amp;&#160;</td>
          <td class="paramname"><em>color</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span><span class="mlabel">static</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Extract the red channel from a color </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">color</td><td>the color to process </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the color red channel </dd></dl>

</div>
</div>
<a class="anchor" id="a3e3a8e355ee733ac09ae1f10db9b57d0"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">ColorChannel NRE::Micro::Color::getB </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the blue channel </dd></dl>

</div>
</div>
<a class="anchor" id="a724e75202b5bdfc0b64e5c1b0d9a0e9f"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">constexpr CompressedColor NRE::Micro::Color::getColor </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the compressed 32 bits color </dd></dl>

</div>
</div>
<a class="anchor" id="a12f1cee974aad505f24f8287f8a970cf"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">ColorChannel NRE::Micro::Color::getG </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the green channel </dd></dl>

</div>
</div>
<a class="anchor" id="a990af7dcc72d09ca41de6f8d1277625b"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">ColorChannel NRE::Micro::Color::getR </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the red channel </dd></dl>

</div>
</div>
<a class="anchor" id="a81e0b2b65ecf8e672ba31f1691a3be75"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php">Color</a>&amp; NRE::Micro::Color::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php">Color</a> const &amp;&#160;</td>
          <td class="paramname"><em>c</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy assign c into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">c</td><td>the color to copy </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="a54ebd96ab6544209832237765e7afc22"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php">Color</a>&amp; NRE::Micro::Color::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php">Color</a> &amp;&amp;&#160;</td>
          <td class="paramname"><em>c</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move assign c into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">c</td><td>the color to move </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="aafcd2a06071ec32b4f6e7ac9a2d0d6a4"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Micro::Color::setB </td>
          <td>(</td>
          <td class="paramtype">ColorChannel&#160;</td>
          <td class="paramname"><em>blue</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Set the blue channel value </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">blue</td><td>the new value </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a1089d94cf65cff8dac8da2da6af8bcd0"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Micro::Color::setG </td>
          <td>(</td>
          <td class="paramtype">ColorChannel&#160;</td>
          <td class="paramname"><em>green</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Set the green channel value </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">green</td><td>the new value </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a75ca29d00bb4353423ed452913ebe3f5"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Micro::Color::setR </td>
          <td>(</td>
          <td class="paramtype">ColorChannel&#160;</td>
          <td class="paramname"><em>red</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Set the red channel value </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">red</td><td>the new value </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<hr/>The documentation for this class was generated from the following files:<ul>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-Micro/src/LED/Color/<a class="el" href="_n_r_e___color_8hpp_source.php">NRE_Color.hpp</a></li>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-Micro/src/LED/Color/<a class="el" href="_n_r_e___color_inl_8hpp_source.php">NRE_ColorInl.hpp</a></li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
