<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Micro: NRE::Micro::Effect Class Reference</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>Micro</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_micro_1_1_effect.php">Effect</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="class_n_r_e_1_1_micro_1_1_effect-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">NRE::Micro::Effect Class Reference<span class="mlabels"><span class="mlabel">abstract</span></span></div>  </div>
</div><!--header-->
<div class="contents">

<p>Represent a light effect.  
 <a href="class_n_r_e_1_1_micro_1_1_effect.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="_n_r_e___effect_8hpp_source.php">NRE_Effect.hpp</a>&gt;</code></p>
<div class="dynheader">
Inheritance diagram for NRE::Micro::Effect:</div>
<div class="dyncontent">
 <div class="center">
  <img src="class_n_r_e_1_1_micro_1_1_effect.png" usemap="#NRE::Micro::Effect_map" alt=""/>
  <map id="NRE::Micro::Effect_map" name="NRE::Micro::Effect_map">
<area href="class_n_r_e_1_1_micro_1_1_fix_effect.php" title="Represent a fix light effect, setting all leds to the same color with no movement. " alt="NRE::Micro::FixEffect" shape="rect" coords="0,56,167,80"/>
<area href="class_n_r_e_1_1_micro_1_1_rotate_effect.php" title="Represent a rotate light effect, setting leds on one by one, only one led remain on at the same time..." alt="NRE::Micro::RotateEffect" shape="rect" coords="177,56,344,80"/>
<area href="class_n_r_e_1_1_micro_1_1_rotate_fix_effect.php" title="Represent a rotate light effect, setting leds on one by one, leds remains on while the effect is runn..." alt="NRE::Micro::RotateFixEffect" shape="rect" coords="354,56,521,80"/>
<area href="class_n_r_e_1_1_micro_1_1_wave_effect.php" title="Represent a wave light effect, setting all leds to the same color, starting from black to the given c..." alt="NRE::Micro::WaveEffect" shape="rect" coords="531,56,698,80"/>
</map>
 </div></div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a5369c806d8afbfc2024b66ebcbbc1403"><td class="memItemLeft" align="right" valign="top">virtual void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_effect.php#a5369c806d8afbfc2024b66ebcbbc1403">start</a> (<a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php">LedController</a> &amp;controller)=0</td></tr>
<tr class="separator:a5369c806d8afbfc2024b66ebcbbc1403"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a0c17b719e2f4974cfc75ba52b25adb83"><td class="memItemLeft" align="right" valign="top">virtual void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_effect.php#a0c17b719e2f4974cfc75ba52b25adb83">run</a> (<a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php">LedController</a> &amp;controller)=0</td></tr>
<tr class="separator:a0c17b719e2f4974cfc75ba52b25adb83"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a146b60fdfbad0c0b02fcbc37fe3c5043"><td class="memItemLeft" align="right" valign="top">virtual void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_effect.php#a146b60fdfbad0c0b02fcbc37fe3c5043">stop</a> (<a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php">LedController</a> &amp;controller)=0</td></tr>
<tr class="separator:a146b60fdfbad0c0b02fcbc37fe3c5043"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>Represent a light effect. </p>
</div><h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="a0c17b719e2f4974cfc75ba52b25adb83"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">virtual void NRE::Micro::Effect::run </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php">LedController</a> &amp;&#160;</td>
          <td class="paramname"><em>controller</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">pure virtual</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Called at each loop iteration </p>

<p>Implemented in <a class="el" href="class_n_r_e_1_1_micro_1_1_rotate_fix_effect.php#a79f9ca1a5b2bee5991558adef2a65341">NRE::Micro::RotateFixEffect</a>, <a class="el" href="class_n_r_e_1_1_micro_1_1_rotate_effect.php#ae427f12101dc8334910db2a7c4d34c3e">NRE::Micro::RotateEffect</a>, <a class="el" href="class_n_r_e_1_1_micro_1_1_wave_effect.php#a5f8489eccf165da3f63acc81fdf8e7d5">NRE::Micro::WaveEffect</a>, and <a class="el" href="class_n_r_e_1_1_micro_1_1_fix_effect.php#a1accc8bbcfbc1ac2fef3e10bb2ed7f2e">NRE::Micro::FixEffect</a>.</p>

</div>
</div>
<a class="anchor" id="a5369c806d8afbfc2024b66ebcbbc1403"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">virtual void NRE::Micro::Effect::start </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php">LedController</a> &amp;&#160;</td>
          <td class="paramname"><em>controller</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">pure virtual</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Called when the effect is set to a controller </p>

<p>Implemented in <a class="el" href="class_n_r_e_1_1_micro_1_1_rotate_fix_effect.php#a1834123e636878bdcf35c45bd258a407">NRE::Micro::RotateFixEffect</a>, <a class="el" href="class_n_r_e_1_1_micro_1_1_rotate_effect.php#aaa0cb4d33076af4cd850b953f6bf24af">NRE::Micro::RotateEffect</a>, <a class="el" href="class_n_r_e_1_1_micro_1_1_wave_effect.php#adde9092c877e9b19ab9c416d0f1d4379">NRE::Micro::WaveEffect</a>, and <a class="el" href="class_n_r_e_1_1_micro_1_1_fix_effect.php#acd3cec3a646da0655464290af02947a5">NRE::Micro::FixEffect</a>.</p>

</div>
</div>
<a class="anchor" id="a146b60fdfbad0c0b02fcbc37fe3c5043"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">virtual void NRE::Micro::Effect::stop </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php">LedController</a> &amp;&#160;</td>
          <td class="paramname"><em>controller</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">pure virtual</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Called when the effect is replaced by another one in a controller </p>

<p>Implemented in <a class="el" href="class_n_r_e_1_1_micro_1_1_rotate_fix_effect.php#a0914e8c393cef1837a39110f98e2383e">NRE::Micro::RotateFixEffect</a>, <a class="el" href="class_n_r_e_1_1_micro_1_1_wave_effect.php#a4cecbf43bd264e786bf42e22734dac98">NRE::Micro::WaveEffect</a>, <a class="el" href="class_n_r_e_1_1_micro_1_1_rotate_effect.php#a26a4eac70d0b03d2265c8279de949583">NRE::Micro::RotateEffect</a>, and <a class="el" href="class_n_r_e_1_1_micro_1_1_fix_effect.php#aca4d9553c6b265f7b6f4add0ff1dd3ca">NRE::Micro::FixEffect</a>.</p>

</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-Micro/src/LED/Effect/<a class="el" href="_n_r_e___effect_8hpp_source.php">NRE_Effect.hpp</a></li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
