<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Micro: NRE::Micro::Led Class Reference</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>Micro</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_micro_1_1_led.php">Led</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="class_n_r_e_1_1_micro_1_1_led-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">NRE::Micro::Led Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>Represent a single <a class="el" href="class_n_r_e_1_1_micro_1_1_led.php" title="Represent a single Led. ">Led</a>.  
 <a href="class_n_r_e_1_1_micro_1_1_led.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="_n_r_e___led_controller_8hpp_source.php">NRE_LedController.hpp</a>&gt;</code></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a3d47f7f1317221084b4571ae261c34f8"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_led.php#a3d47f7f1317221084b4571ae261c34f8">Led</a> ()=delete</td></tr>
<tr class="separator:a3d47f7f1317221084b4571ae261c34f8"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8b166a24c3fe7c0beb4dd50e4015f4d8"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_led.php#a8b166a24c3fe7c0beb4dd50e4015f4d8">Led</a> (LedId i, <a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php">LedController</a> *ctr)</td></tr>
<tr class="separator:a8b166a24c3fe7c0beb4dd50e4015f4d8"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9d9a567a29256a0c2a140af2960d0274"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_led.php#a9d9a567a29256a0c2a140af2960d0274">Led</a> (<a class="el" href="class_n_r_e_1_1_micro_1_1_led.php">Led</a> const &amp;led)=default</td></tr>
<tr class="separator:a9d9a567a29256a0c2a140af2960d0274"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9fa0112e56055825ce4005ccabe190f6"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_led.php#a9fa0112e56055825ce4005ccabe190f6">Led</a> (<a class="el" href="class_n_r_e_1_1_micro_1_1_led.php">Led</a> &amp;&amp;led)=default</td></tr>
<tr class="separator:a9fa0112e56055825ce4005ccabe190f6"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a144cb7e189a4850cf3f5c045c45d5fab"><td class="memItemLeft" align="right" valign="top">CompressedColor&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_led.php#a144cb7e189a4850cf3f5c045c45d5fab">getColor</a> () const </td></tr>
<tr class="separator:a144cb7e189a4850cf3f5c045c45d5fab"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a84e8281436fa31ffbb4eb39ef6aaba4b"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_led.php#a84e8281436fa31ffbb4eb39ef6aaba4b">setColor</a> (<a class="el" href="class_n_r_e_1_1_micro_1_1_color.php">Color</a> const &amp;color)</td></tr>
<tr class="separator:a84e8281436fa31ffbb4eb39ef6aaba4b"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a2624fb34732b14e2eb7f9880c99786cb"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_led.php#a2624fb34732b14e2eb7f9880c99786cb">setColorHandle</a> (std::function&lt; void(<a class="el" href="class_n_r_e_1_1_micro_1_1_color.php">Color</a> &amp;)&gt; handle)</td></tr>
<tr class="separator:a2624fb34732b14e2eb7f9880c99786cb"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a25bef4d3e5d9463190c55e4a2bfd447c"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_led.php#a25bef4d3e5d9463190c55e4a2bfd447c">update</a> (<a class="el" href="class_n_r_e_1_1_micro_1_1_color.php">Color</a> const &amp;color)</td></tr>
<tr class="separator:a25bef4d3e5d9463190c55e4a2bfd447c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a922510060cd8947bad521fa47a5ee028"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_led.php#a922510060cd8947bad521fa47a5ee028">turnOff</a> () const </td></tr>
<tr class="separator:a922510060cd8947bad521fa47a5ee028"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8834d8f177b8ab098b107020de280ef2"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_led.php#a8834d8f177b8ab098b107020de280ef2">turnOn</a> () const </td></tr>
<tr class="separator:a8834d8f177b8ab098b107020de280ef2"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a26b3dd23f82e48c2d3c6c367a10e81e3"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_micro_1_1_led.php">Led</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_led.php#a26b3dd23f82e48c2d3c6c367a10e81e3">operator=</a> (<a class="el" href="class_n_r_e_1_1_micro_1_1_led.php">Led</a> const &amp;led)=default</td></tr>
<tr class="separator:a26b3dd23f82e48c2d3c6c367a10e81e3"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac3d3400cc28114d902cb8a03f77e30b6"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_micro_1_1_led.php">Led</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_led.php#ac3d3400cc28114d902cb8a03f77e30b6">operator=</a> (<a class="el" href="class_n_r_e_1_1_micro_1_1_led.php">Led</a> &amp;&amp;led)=default</td></tr>
<tr class="separator:ac3d3400cc28114d902cb8a03f77e30b6"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>Represent a single <a class="el" href="class_n_r_e_1_1_micro_1_1_led.php" title="Represent a single Led. ">Led</a>. </p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="a3d47f7f1317221084b4571ae261c34f8"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Micro::Led::Led </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>No default constructor </p>

</div>
</div>
<a class="anchor" id="a8b166a24c3fe7c0beb4dd50e4015f4d8"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Micro::Led::Led </td>
          <td>(</td>
          <td class="paramtype">LedId&#160;</td>
          <td class="paramname"><em>i</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php">LedController</a> *&#160;</td>
          <td class="paramname"><em>ctr</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Construct the led from the controller </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">i</td><td>the led's id </td></tr>
    <tr><td class="paramname">ctr</td><td>the leds controller </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a9d9a567a29256a0c2a140af2960d0274"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Micro::Led::Led </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_micro_1_1_led.php">Led</a> const &amp;&#160;</td>
          <td class="paramname"><em>led</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy led into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">led</td><td>the led to copy </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a9fa0112e56055825ce4005ccabe190f6"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Micro::Led::Led </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_micro_1_1_led.php">Led</a> &amp;&amp;&#160;</td>
          <td class="paramname"><em>led</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move led into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">led</td><td>the led to move </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="a144cb7e189a4850cf3f5c045c45d5fab"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">CompressedColor NRE::Micro::Led::getColor </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the internal compressed color </dd></dl>

</div>
</div>
<a class="anchor" id="a26b3dd23f82e48c2d3c6c367a10e81e3"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_micro_1_1_led.php">Led</a>&amp; NRE::Micro::Led::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_micro_1_1_led.php">Led</a> const &amp;&#160;</td>
          <td class="paramname"><em>led</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy assign led into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">led</td><td>the led to copy </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="ac3d3400cc28114d902cb8a03f77e30b6"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_micro_1_1_led.php">Led</a>&amp; NRE::Micro::Led::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_micro_1_1_led.php">Led</a> &amp;&amp;&#160;</td>
          <td class="paramname"><em>led</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move assign led into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">led</td><td>the led to move </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="a84e8281436fa31ffbb4eb39ef6aaba4b"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Micro::Led::setColor </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php">Color</a> const &amp;&#160;</td>
          <td class="paramname"><em>color</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Set the led color </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">color</td><td>the new color </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a2624fb34732b14e2eb7f9880c99786cb"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Micro::Led::setColorHandle </td>
          <td>(</td>
          <td class="paramtype">std::function&lt; void(<a class="el" href="class_n_r_e_1_1_micro_1_1_color.php">Color</a> &amp;)&gt;&#160;</td>
          <td class="paramname"><em>handle</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Set the color changes handles </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">handle</td><td>the new handler </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a922510060cd8947bad521fa47a5ee028"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Micro::Led::turnOff </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Turn off the led </p>

</div>
</div>
<a class="anchor" id="a8834d8f177b8ab098b107020de280ef2"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Micro::Led::turnOn </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Turn on the led </p>

</div>
</div>
<a class="anchor" id="a25bef4d3e5d9463190c55e4a2bfd447c"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Micro::Led::update </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php">Color</a> const &amp;&#160;</td>
          <td class="paramname"><em>color</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Update the led color </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">color</td><td>the new color </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<hr/>The documentation for this class was generated from the following files:<ul>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-Micro/src/LED/Controller/<a class="el" href="_n_r_e___led_controller_8hpp_source.php">NRE_LedController.hpp</a></li>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-Micro/src/LED/Controller/<a class="el" href="_n_r_e___led_inl_8hpp_source.php">NRE_LedInl.hpp</a></li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
