<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Micro: Member List</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>Micro</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php">Color</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE::Micro::Color Member List</div>  </div>
</div><!--header-->
<div class="contents">

<p>This is the complete list of members for <a class="el" href="class_n_r_e_1_1_micro_1_1_color.php">NRE::Micro::Color</a>, including all inherited members.</p>
<table class="directory">
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php#a4e5a2d8b901b97ba413a67cc5b43b597">Color</a>()=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php">NRE::Micro::Color</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php#ac4755c79a12aa581d38c95d35aebd8ce">Color</a>(ColorChannel red, ColorChannel green, ColorChannel blue)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php">NRE::Micro::Color</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php#aff5a13a11e5ed0b490be89a320475dfe">Color</a>(CompressedColor color)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php">NRE::Micro::Color</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php#a9b85cf58034515554496ee4153065169">Color</a>(Color const &amp;c)=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php">NRE::Micro::Color</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php#ad4e3c5aca1fd3a4426d1b222ba3b83c3">Color</a>(Color &amp;&amp;c)=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php">NRE::Micro::Color</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php#a5912ab8577748c36a5896924ed326b8a">extractB</a>(CompressedColor color)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php">NRE::Micro::Color</a></td><td class="entry"><span class="mlabel">inline</span><span class="mlabel">static</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php#a95b36171d189b73f635cad6eeb0bc8b4">extractB</a>(Color const &amp;color)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php">NRE::Micro::Color</a></td><td class="entry"><span class="mlabel">inline</span><span class="mlabel">static</span></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php#ad83102ad4e6250d498e99a6ede2a5051">extractG</a>(CompressedColor color)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php">NRE::Micro::Color</a></td><td class="entry"><span class="mlabel">inline</span><span class="mlabel">static</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php#a84fe855a786f4f39d64eed3f874609b3">extractG</a>(Color const &amp;color)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php">NRE::Micro::Color</a></td><td class="entry"><span class="mlabel">inline</span><span class="mlabel">static</span></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php#a866fa6ed8ce1aa378ba92a97e5c0d7f0">extractR</a>(CompressedColor color)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php">NRE::Micro::Color</a></td><td class="entry"><span class="mlabel">inline</span><span class="mlabel">static</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php#ae6f843b4e3974141004b54fccca9978d">extractR</a>(Color const &amp;color)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php">NRE::Micro::Color</a></td><td class="entry"><span class="mlabel">inline</span><span class="mlabel">static</span></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php#a3e3a8e355ee733ac09ae1f10db9b57d0">getB</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php">NRE::Micro::Color</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php#a724e75202b5bdfc0b64e5c1b0d9a0e9f">getColor</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php">NRE::Micro::Color</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php#a12f1cee974aad505f24f8287f8a970cf">getG</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php">NRE::Micro::Color</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php#a990af7dcc72d09ca41de6f8d1277625b">getR</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php">NRE::Micro::Color</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php#a81e0b2b65ecf8e672ba31f1691a3be75">operator=</a>(Color const &amp;c)=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php">NRE::Micro::Color</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php#a54ebd96ab6544209832237765e7afc22">operator=</a>(Color &amp;&amp;c)=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php">NRE::Micro::Color</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php#aafcd2a06071ec32b4f6e7ac9a2d0d6a4">setB</a>(ColorChannel blue)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php">NRE::Micro::Color</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php#a1089d94cf65cff8dac8da2da6af8bcd0">setG</a>(ColorChannel green)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php">NRE::Micro::Color</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php#a75ca29d00bb4353423ed452913ebe3f5">setR</a>(ColorChannel red)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php">NRE::Micro::Color</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
</table></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
