<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Micro: Member List</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>Micro</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php">ObservedData</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE::Micro::ObservedData&lt; T &gt; Member List</div>  </div>
</div><!--header-->
<div class="contents">

<p>This is the complete list of members for <a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php">NRE::Micro::ObservedData&lt; T &gt;</a>, including all inherited members.</p>
<table class="directory">
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_abstract_data.php#ace46a0e36fc28878ffa0e26c7bd27a10">AbstractData</a>()=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_abstract_data.php">NRE::Micro::AbstractData</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php#a31c5da057567efa27459fed706756764">get</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php">NRE::Micro::ObservedData&lt; T &gt;</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php#aff025bb7f4f1a2eb56849035f117e77e">get</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php">NRE::Micro::ObservedData&lt; T &gt;</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php#ac6e7dc7c3ed3996279d9f2d3b87a1e14">getSize</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php">NRE::Micro::ObservedData&lt; T &gt;</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr bgcolor="#f0f0f0" class="even"><td class="entry"><b>getSize</b>() const (defined in <a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php">NRE::Micro::ObservedData&lt; T &gt;</a>)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php">NRE::Micro::ObservedData&lt; T &gt;</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php#ab206accc4946fb61c4e6f400c707e54c">ObservedData</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php">NRE::Micro::ObservedData&lt; T &gt;</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php#a39840504a2dcdde7342ed7d79035c59d">ObservedData</a>(Args &amp;&amp;...args)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php">NRE::Micro::ObservedData&lt; T &gt;</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php#ad121e35abe75a1a8b8ab43a33fe1517d">ObservedData</a>(ObservedData const &amp;d)=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php">NRE::Micro::ObservedData&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php#abc19deb348e88c9b397a49f2f732686f">ObservedData</a>(ObservedData &amp;&amp;d)=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php">NRE::Micro::ObservedData&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php#a8133192991e7b9147b7fa60cb5ca8b1b">operator=</a>(ObservedData const &amp;d)=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php">NRE::Micro::ObservedData&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php#af5cdfe061d29cacb5a75fb8d4cde419b">operator=</a>(ObservedData &amp;&amp;d)=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php">NRE::Micro::ObservedData&lt; T &gt;</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php#a4cc8da2e5a78b07b832b918269f965f2">operator=</a>(T const &amp;d)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php">NRE::Micro::ObservedData&lt; T &gt;</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php#a06f3611468d03b1ca19a8136ca83348d">operator=</a>(T &amp;&amp;d)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php">NRE::Micro::ObservedData&lt; T &gt;</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php#a2527354b4a42cdd8ca2a13b3a1bfdb10">setHandle</a>(std::function&lt; void(T &amp;)&gt; h)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php">NRE::Micro::ObservedData&lt; T &gt;</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php#ae31524de97b82aaa75dad2f17a93b5db">update</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php">NRE::Micro::ObservedData&lt; T &gt;</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php#a6637913e8e42efad032d35db11c064ad">~ObservedData</a>()=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php">NRE::Micro::ObservedData&lt; T &gt;</a></td><td class="entry"></td></tr>
</table></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
