<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Micro: NRE::Micro::WebManager Class Reference</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>Micro</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_micro_1_1_web_manager.php">WebManager</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="class_n_r_e_1_1_micro_1_1_web_manager-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">NRE::Micro::WebManager Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>Manage a web serveur and http updater.  
 <a href="class_n_r_e_1_1_micro_1_1_web_manager.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="_n_r_e___web_manager_8hpp_source.php">NRE_WebManager.hpp</a>&gt;</code></p>
<div class="dynheader">
Inheritance diagram for NRE::Micro::WebManager:</div>
<div class="dyncontent">
 <div class="center">
  <img src="class_n_r_e_1_1_micro_1_1_web_manager.png" usemap="#NRE::Micro::WebManager_map" alt=""/>
  <map id="NRE::Micro::WebManager_map" name="NRE::Micro::WebManager_map">
<area href="class_n_r_e_1_1_micro_1_1_module.php" alt="NRE::Micro::Module&lt; WebManager &gt;" shape="rect" coords="0,56,224,80"/>
<area href="class_n_r_e_1_1_micro_1_1_abstract_module.php" title="Represent an abstract module used to active a certain part of the framework. " alt="NRE::Micro::AbstractModule" shape="rect" coords="0,0,224,24"/>
</map>
 </div></div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a9ecc75f34d80a10da66edf8afbc47fc8"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_web_manager.php#a9ecc75f34d80a10da66edf8afbc47fc8">WebManager</a> ()</td></tr>
<tr class="separator:a9ecc75f34d80a10da66edf8afbc47fc8"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a6ea119278f71be42f465f72f2aceb499"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_web_manager.php#a6ea119278f71be42f465f72f2aceb499">addHandle</a> (ServerHandle handler)</td></tr>
<tr class="separator:a6ea119278f71be42f465f72f2aceb499"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a0a051633dc4a2f90579ea83819980641"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_web_manager.php#a0a051633dc4a2f90579ea83819980641">setup</a> () override</td></tr>
<tr class="separator:a0a051633dc4a2f90579ea83819980641"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a83547254a117ec8c8f35909759909557"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_web_manager.php#a83547254a117ec8c8f35909759909557">loop</a> () override</td></tr>
<tr class="separator:a83547254a117ec8c8f35909759909557"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="inherit_header pub_methods_class_n_r_e_1_1_micro_1_1_module"><td colspan="2" onclick="javascript:toggleInherit('pub_methods_class_n_r_e_1_1_micro_1_1_module')"><img src="closed.png" alt="-"/>&#160;Public Member Functions inherited from <a class="el" href="class_n_r_e_1_1_micro_1_1_module.php">NRE::Micro::Module&lt; WebManager &gt;</a></td></tr>
<tr class="memitem:ab8051683526e308ef6d0c878ccfb9fe2 inherit pub_methods_class_n_r_e_1_1_micro_1_1_module"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_module.php#ab8051683526e308ef6d0c878ccfb9fe2">Module</a> ()</td></tr>
<tr class="separator:ab8051683526e308ef6d0c878ccfb9fe2 inherit pub_methods_class_n_r_e_1_1_micro_1_1_module"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab4e431b60f84d4b499c9315cf4502f4b inherit pub_methods_class_n_r_e_1_1_micro_1_1_module"><td class="memItemLeft" align="right" valign="top">virtual&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_module.php#ab4e431b60f84d4b499c9315cf4502f4b">~Module</a> ()=default</td></tr>
<tr class="separator:ab4e431b60f84d4b499c9315cf4502f4b inherit pub_methods_class_n_r_e_1_1_micro_1_1_module"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="inherit_header pub_methods_class_n_r_e_1_1_micro_1_1_abstract_module"><td colspan="2" onclick="javascript:toggleInherit('pub_methods_class_n_r_e_1_1_micro_1_1_abstract_module')"><img src="closed.png" alt="-"/>&#160;Public Member Functions inherited from <a class="el" href="class_n_r_e_1_1_micro_1_1_abstract_module.php">NRE::Micro::AbstractModule</a></td></tr>
<tr class="memitem:aa3db66bc689eb07168e52157e6cf1702 inherit pub_methods_class_n_r_e_1_1_micro_1_1_abstract_module"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_abstract_module.php#aa3db66bc689eb07168e52157e6cf1702">AbstractModule</a> ()=default</td></tr>
<tr class="separator:aa3db66bc689eb07168e52157e6cf1702 inherit pub_methods_class_n_r_e_1_1_micro_1_1_abstract_module"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a38f613f697ca8d200a1a270e03967d04 inherit pub_methods_class_n_r_e_1_1_micro_1_1_abstract_module"><td class="memItemLeft" align="right" valign="top">virtual&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_abstract_module.php#a38f613f697ca8d200a1a270e03967d04">~AbstractModule</a> ()=default</td></tr>
<tr class="separator:a38f613f697ca8d200a1a270e03967d04 inherit pub_methods_class_n_r_e_1_1_micro_1_1_abstract_module"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a6aef5a0cbb4fb0b08e8b77f3ff5076b0 inherit pub_methods_class_n_r_e_1_1_micro_1_1_abstract_module"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_abstract_module.php#a6aef5a0cbb4fb0b08e8b77f3ff5076b0">AbstractModule</a> (<a class="el" href="class_n_r_e_1_1_micro_1_1_abstract_module.php">AbstractModule</a> const &amp;m)=delete</td></tr>
<tr class="separator:a6aef5a0cbb4fb0b08e8b77f3ff5076b0 inherit pub_methods_class_n_r_e_1_1_micro_1_1_abstract_module"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad67ca9dc2add373f389afa03d17e3c0f inherit pub_methods_class_n_r_e_1_1_micro_1_1_abstract_module"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_abstract_module.php#ad67ca9dc2add373f389afa03d17e3c0f">AbstractModule</a> (<a class="el" href="class_n_r_e_1_1_micro_1_1_abstract_module.php">AbstractModule</a> &amp;&amp;m)=delete</td></tr>
<tr class="separator:ad67ca9dc2add373f389afa03d17e3c0f inherit pub_methods_class_n_r_e_1_1_micro_1_1_abstract_module"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a2452ab1a95d5dd5c4305605ed4243492 inherit pub_methods_class_n_r_e_1_1_micro_1_1_abstract_module"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_micro_1_1_abstract_module.php">AbstractModule</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_abstract_module.php#a2452ab1a95d5dd5c4305605ed4243492">operator=</a> (<a class="el" href="class_n_r_e_1_1_micro_1_1_abstract_module.php">AbstractModule</a> const &amp;m)=delete</td></tr>
<tr class="separator:a2452ab1a95d5dd5c4305605ed4243492 inherit pub_methods_class_n_r_e_1_1_micro_1_1_abstract_module"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a2f01e20c0f30f2e706af1dfdea3b591b inherit pub_methods_class_n_r_e_1_1_micro_1_1_abstract_module"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_micro_1_1_abstract_module.php">AbstractModule</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_abstract_module.php#a2f01e20c0f30f2e706af1dfdea3b591b">operator=</a> (<a class="el" href="class_n_r_e_1_1_micro_1_1_abstract_module.php">AbstractModule</a> &amp;&amp;m)=delete</td></tr>
<tr class="separator:a2f01e20c0f30f2e706af1dfdea3b591b inherit pub_methods_class_n_r_e_1_1_micro_1_1_abstract_module"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="inherited"></a>
Additional Inherited Members</h2></td></tr>
<tr class="inherit_header pub_static_methods_class_n_r_e_1_1_micro_1_1_module"><td colspan="2" onclick="javascript:toggleInherit('pub_static_methods_class_n_r_e_1_1_micro_1_1_module')"><img src="closed.png" alt="-"/>&#160;Static Public Member Functions inherited from <a class="el" href="class_n_r_e_1_1_micro_1_1_module.php">NRE::Micro::Module&lt; WebManager &gt;</a></td></tr>
<tr class="memitem:a6d9a8c837f180ffd064224d06d9f42e4 inherit pub_static_methods_class_n_r_e_1_1_micro_1_1_module"><td class="memItemLeft" align="right" valign="top">static ModuleId&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_module.php#a6d9a8c837f180ffd064224d06d9f42e4">getId</a> ()</td></tr>
<tr class="separator:a6d9a8c837f180ffd064224d06d9f42e4 inherit pub_static_methods_class_n_r_e_1_1_micro_1_1_module"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="inherit_header pub_static_attribs_class_n_r_e_1_1_micro_1_1_abstract_module"><td colspan="2" onclick="javascript:toggleInherit('pub_static_attribs_class_n_r_e_1_1_micro_1_1_abstract_module')"><img src="closed.png" alt="-"/>&#160;Static Public Attributes inherited from <a class="el" href="class_n_r_e_1_1_micro_1_1_abstract_module.php">NRE::Micro::AbstractModule</a></td></tr>
<tr class="memitem:a95d15910d0d4e77aa08063fe383ff8dc inherit pub_static_attribs_class_n_r_e_1_1_micro_1_1_abstract_module"><td class="memItemLeft" align="right" valign="top">static ModuleId&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_abstract_module.php#a95d15910d0d4e77aa08063fe383ff8dc">counter</a> = 0</td></tr>
<tr class="separator:a95d15910d0d4e77aa08063fe383ff8dc inherit pub_static_attribs_class_n_r_e_1_1_micro_1_1_abstract_module"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>Manage a web serveur and http updater. </p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="a9ecc75f34d80a10da66edf8afbc47fc8"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Micro::WebManager::WebManager </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Construct the web module </p>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="a6ea119278f71be42f465f72f2aceb499"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Micro::WebManager::addHandle </td>
          <td>(</td>
          <td class="paramtype">ServerHandle&#160;</td>
          <td class="paramname"><em>handler</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Add a server handle to the internal web server </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">handler</td><td>the handle function </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a83547254a117ec8c8f35909759909557"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Micro::WebManager::loop </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span><span class="mlabel">override</span><span class="mlabel">virtual</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>The module loop </p>

<p>Reimplemented from <a class="el" href="class_n_r_e_1_1_micro_1_1_abstract_module.php#a62533d0ef5768f92707d413d53fb3904">NRE::Micro::AbstractModule</a>.</p>

</div>
</div>
<a class="anchor" id="a0a051633dc4a2f90579ea83819980641"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Micro::WebManager::setup </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span><span class="mlabel">override</span><span class="mlabel">virtual</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Setup the module </p>

<p>Reimplemented from <a class="el" href="class_n_r_e_1_1_micro_1_1_abstract_module.php#a8f93564ffc4fa3818c765b6eed3ab083">NRE::Micro::AbstractModule</a>.</p>

</div>
</div>
<hr/>The documentation for this class was generated from the following files:<ul>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-Micro/src/Web/Manager/<a class="el" href="_n_r_e___web_manager_8hpp_source.php">NRE_WebManager.hpp</a></li>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-Micro/src/Web/Manager/<a class="el" href="_n_r_e___web_manager_inl_8hpp_source.php">NRE_WebManagerInl.hpp</a></li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
