<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Micro: Member List</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>Micro</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php">MicroManager</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE::Micro::MicroManager Member List</div>  </div>
</div><!--header-->
<div class="contents">

<p>This is the complete list of members for <a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php">NRE::Micro::MicroManager</a>, including all inherited members.</p>
<table class="directory">
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#a30db23a789e19edbe1547c1f3b38f85c">add</a>(SubModule *module)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php">NRE::Micro::MicroManager</a></td><td class="entry"><span class="mlabel">inline</span><span class="mlabel">static</span></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#aea38fe1e1b792700bc032cb8471ab028">addModule</a>(SubModule *module)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php">NRE::Micro::MicroManager</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#a0e8afcf29c4af96d8b26172b9c266879">get</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php">NRE::Micro::MicroManager</a></td><td class="entry"><span class="mlabel">inline</span><span class="mlabel">static</span></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#a5810aa873a9ba19a2f0737b383cedb33">get</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php">NRE::Micro::MicroManager</a></td><td class="entry"><span class="mlabel">inline</span><span class="mlabel">static</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#abae5088c23e05992e055aaa14a332ab9">getModule</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php">NRE::Micro::MicroManager</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#ae353a1ea48369af4c9783977b2b9995a">loop</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php">NRE::Micro::MicroManager</a></td><td class="entry"><span class="mlabel">inline</span><span class="mlabel">static</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#aa1fce2c43a932cce99e74e8423fe8099">loopModules</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php">NRE::Micro::MicroManager</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#a69fb44d8d24a58ed84866f5be95ee6be">MicroManager</a>()=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php">NRE::Micro::MicroManager</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#aed7cb06d6e864e410f87cd45047af556">MicroManager</a>(MicroManager const &amp;mng)=delete</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php">NRE::Micro::MicroManager</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#ac48667370b771b06f12ae3b7a9f1609f">MicroManager</a>(MicroManager &amp;&amp;mng)=delete</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php">NRE::Micro::MicroManager</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#a392856201b2ab654762f8a6bfa4fa0d8">operator=</a>(MicroManager const &amp;mng)=delete</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php">NRE::Micro::MicroManager</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#a04b10ab9a31b149214864888cfec6617">operator=</a>(MicroManager &amp;&amp;mng)=delete</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php">NRE::Micro::MicroManager</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#a8d9a10df1225539a2dcde55dd7c6ed32">setup</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php">NRE::Micro::MicroManager</a></td><td class="entry"><span class="mlabel">inline</span><span class="mlabel">static</span></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#a39f9b0ec9a1d09b092fb833cf41c32cd">setupModules</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php">NRE::Micro::MicroManager</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#a321ee576959f42775fbde9d4a092f7e2">~MicroManager</a>()=default</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php">NRE::Micro::MicroManager</a></td><td class="entry"></td></tr>
</table></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
