<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Micro: NRE::Micro::RotateEffect Class Reference</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>Micro</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_micro_1_1_rotate_effect.php">RotateEffect</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="class_n_r_e_1_1_micro_1_1_rotate_effect-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">NRE::Micro::RotateEffect Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>Represent a rotate light effect, setting leds on one by one, only one led remain on at the same time.  
 <a href="class_n_r_e_1_1_micro_1_1_rotate_effect.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="_n_r_e___rotate_effect_8hpp_source.php">NRE_RotateEffect.hpp</a>&gt;</code></p>
<div class="dynheader">
Inheritance diagram for NRE::Micro::RotateEffect:</div>
<div class="dyncontent">
 <div class="center">
  <img src="class_n_r_e_1_1_micro_1_1_rotate_effect.png" usemap="#NRE::Micro::RotateEffect_map" alt=""/>
  <map id="NRE::Micro::RotateEffect_map" name="NRE::Micro::RotateEffect_map">
<area href="class_n_r_e_1_1_micro_1_1_effect.php" title="Represent a light effect. " alt="NRE::Micro::Effect" shape="rect" coords="0,0,150,24"/>
</map>
 </div></div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:aa81771165f5a0ef53ce9b63b29ac0f45"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_rotate_effect.php#aa81771165f5a0ef53ce9b63b29ac0f45">RotateEffect</a> ()=delete</td></tr>
<tr class="separator:aa81771165f5a0ef53ce9b63b29ac0f45"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a110dede2e80fc73f21c08006efd08cc7"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_rotate_effect.php#a110dede2e80fc73f21c08006efd08cc7">RotateEffect</a> (<a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php">ObservedData</a>&lt; <a class="el" href="class_n_r_e_1_1_micro_1_1_color.php">Color</a> &gt; &amp;c, unsigned char s=5, bool clockwiseEffect=true)</td></tr>
<tr class="separator:a110dede2e80fc73f21c08006efd08cc7"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aaa0cb4d33076af4cd850b953f6bf24af"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_rotate_effect.php#aaa0cb4d33076af4cd850b953f6bf24af">start</a> (<a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php">LedController</a> &amp;controller) override</td></tr>
<tr class="separator:aaa0cb4d33076af4cd850b953f6bf24af"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae427f12101dc8334910db2a7c4d34c3e"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_rotate_effect.php#ae427f12101dc8334910db2a7c4d34c3e">run</a> (<a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php">LedController</a> &amp;controller) override</td></tr>
<tr class="separator:ae427f12101dc8334910db2a7c4d34c3e"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a26a4eac70d0b03d2265c8279de949583"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_rotate_effect.php#a26a4eac70d0b03d2265c8279de949583">stop</a> (<a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php">LedController</a> &amp;controller) override</td></tr>
<tr class="separator:a26a4eac70d0b03d2265c8279de949583"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>Represent a rotate light effect, setting leds on one by one, only one led remain on at the same time. </p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="aa81771165f5a0ef53ce9b63b29ac0f45"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Micro::RotateEffect::RotateEffect </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>No default constructor </p>

</div>
</div>
<a class="anchor" id="a110dede2e80fc73f21c08006efd08cc7"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Micro::RotateEffect::RotateEffect </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php">ObservedData</a>&lt; <a class="el" href="class_n_r_e_1_1_micro_1_1_color.php">Color</a> &gt; &amp;&#160;</td>
          <td class="paramname"><em>c</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">unsigned char&#160;</td>
          <td class="paramname"><em>s</em> = <code>5</code>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">bool&#160;</td>
          <td class="paramname"><em>clockwiseEffect</em> = <code>true</code>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Construct the effect from the fix color </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">c</td><td>the effect color </td></tr>
    <tr><td class="paramname">s</td><td>the effect speed </td></tr>
    <tr><td class="paramname">clockwiseEffect</td><td>tell if the effect is rotating clockwise or not </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="ae427f12101dc8334910db2a7c4d34c3e"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Micro::RotateEffect::run </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php">LedController</a> &amp;&#160;</td>
          <td class="paramname"><em>controller</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span><span class="mlabel">override</span><span class="mlabel">virtual</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Called at each loop iteration </p>

<p>Implements <a class="el" href="class_n_r_e_1_1_micro_1_1_effect.php#a0c17b719e2f4974cfc75ba52b25adb83">NRE::Micro::Effect</a>.</p>

</div>
</div>
<a class="anchor" id="aaa0cb4d33076af4cd850b953f6bf24af"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Micro::RotateEffect::start </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php">LedController</a> &amp;&#160;</td>
          <td class="paramname"><em>controller</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span><span class="mlabel">override</span><span class="mlabel">virtual</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Called when the effect is set to a controller </p>

<p>Implements <a class="el" href="class_n_r_e_1_1_micro_1_1_effect.php#a5369c806d8afbfc2024b66ebcbbc1403">NRE::Micro::Effect</a>.</p>

</div>
</div>
<a class="anchor" id="a26a4eac70d0b03d2265c8279de949583"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Micro::RotateEffect::stop </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php">LedController</a> &amp;&#160;</td>
          <td class="paramname"><em>controller</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span><span class="mlabel">override</span><span class="mlabel">virtual</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Called when the effect is replaced by another one in a controller </p>

<p>Implements <a class="el" href="class_n_r_e_1_1_micro_1_1_effect.php#a146b60fdfbad0c0b02fcbc37fe3c5043">NRE::Micro::Effect</a>.</p>

</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-Micro/src/LED/Effect/<a class="el" href="_n_r_e___rotate_effect_8hpp_source.php">NRE_RotateEffect.hpp</a></li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
