<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Micro: NRE::Micro::LedController Class Reference</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>Micro</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php">LedController</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-types">Public Types</a> &#124;
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="class_n_r_e_1_1_micro_1_1_led_controller-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">NRE::Micro::LedController Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>Manage access to a led component.  
 <a href="class_n_r_e_1_1_micro_1_1_led_controller.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="_n_r_e___led_controller_8hpp_source.php">NRE_LedController.hpp</a>&gt;</code></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-types"></a>
Public Types</h2></td></tr>
<tr class="memitem:a866e6af4f39ee03e14874fa0a95bd55a"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a866e6af4f39ee03e14874fa0a95bd55a"></a>
typedef <a class="el" href="class_n_r_e_1_1_micro_1_1_led.php">Led</a> *&#160;</td><td class="memItemRight" valign="bottom"><b>Iterator</b></td></tr>
<tr class="separator:a866e6af4f39ee03e14874fa0a95bd55a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af1c2becbaa9c4c0cd9a4e793d24a683c"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="af1c2becbaa9c4c0cd9a4e793d24a683c"></a>
typedef const <a class="el" href="class_n_r_e_1_1_micro_1_1_led.php">Led</a> *&#160;</td><td class="memItemRight" valign="bottom"><b>ConstIterator</b></td></tr>
<tr class="separator:af1c2becbaa9c4c0cd9a4e793d24a683c"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:aca90a1d766338cd467cf927063643c99"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#aca90a1d766338cd467cf927063643c99">LedController</a> ()=delete</td></tr>
<tr class="separator:aca90a1d766338cd467cf927063643c99"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:afe2029cf34f87b8422d70af72a5ab753"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#afe2029cf34f87b8422d70af72a5ab753">LedController</a> (LedId nb, Pin pin, neoPixelType type=NEO_GRB+NEO_KHZ800)</td></tr>
<tr class="separator:afe2029cf34f87b8422d70af72a5ab753"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aff6899eab59d46ee21e03f3c9d126963"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#aff6899eab59d46ee21e03f3c9d126963">LedController</a> (<a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php">LedController</a> const &amp;ctr)=delete</td></tr>
<tr class="separator:aff6899eab59d46ee21e03f3c9d126963"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af096ed8232cd981f1d29d2d15ee97deb"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#af096ed8232cd981f1d29d2d15ee97deb">LedController</a> (<a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php">LedController</a> &amp;&amp;ctr)=delete</td></tr>
<tr class="separator:af096ed8232cd981f1d29d2d15ee97deb"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a1c564c610021c5c9f24dfa8a61ea6faa"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#a1c564c610021c5c9f24dfa8a61ea6faa">~LedController</a> ()</td></tr>
<tr class="separator:a1c564c610021c5c9f24dfa8a61ea6faa"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a82eab1bb15dc21d04b5754d268ab8871"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_micro_1_1_led.php">Iterator</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#a82eab1bb15dc21d04b5754d268ab8871">begin</a> ()</td></tr>
<tr class="separator:a82eab1bb15dc21d04b5754d268ab8871"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aeb0448b85aa79b202cac30fd94bb4e90"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_micro_1_1_led.php">ConstIterator</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#aeb0448b85aa79b202cac30fd94bb4e90">begin</a> () const </td></tr>
<tr class="separator:aeb0448b85aa79b202cac30fd94bb4e90"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a73545f2926f3129379eef377c7123498"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_micro_1_1_led.php">ConstIterator</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#a73545f2926f3129379eef377c7123498">cbegin</a> () const </td></tr>
<tr class="separator:a73545f2926f3129379eef377c7123498"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a14e9ce5ae98856abdef002abf9b6bde1"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_micro_1_1_led.php">Iterator</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#a14e9ce5ae98856abdef002abf9b6bde1">end</a> ()</td></tr>
<tr class="separator:a14e9ce5ae98856abdef002abf9b6bde1"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9a34c7cebe81aeda12baa868ebc30ea7"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_micro_1_1_led.php">ConstIterator</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#a9a34c7cebe81aeda12baa868ebc30ea7">end</a> () const </td></tr>
<tr class="separator:a9a34c7cebe81aeda12baa868ebc30ea7"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a1a2cecffbe7a62ec3a352dbdb0e3a302"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_micro_1_1_led.php">ConstIterator</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#a1a2cecffbe7a62ec3a352dbdb0e3a302">cend</a> () const </td></tr>
<tr class="separator:a1a2cecffbe7a62ec3a352dbdb0e3a302"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab91228876528d9d66b1aa35b078b78e1"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#ab91228876528d9d66b1aa35b078b78e1">turnOff</a> ()</td></tr>
<tr class="separator:ab91228876528d9d66b1aa35b078b78e1"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a7829273c294972a1dcdc4e18e4cada12"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#a7829273c294972a1dcdc4e18e4cada12">turnOff</a> (LedId id)</td></tr>
<tr class="separator:a7829273c294972a1dcdc4e18e4cada12"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a0b8a39b1a9e132de0f7c2fc5127e8ab0"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#a0b8a39b1a9e132de0f7c2fc5127e8ab0">turnOn</a> ()</td></tr>
<tr class="separator:a0b8a39b1a9e132de0f7c2fc5127e8ab0"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a7f94593a8c490635293b7264f78b00a9"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#a7f94593a8c490635293b7264f78b00a9">turnOn</a> (LedId id)</td></tr>
<tr class="separator:a7f94593a8c490635293b7264f78b00a9"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a89faff70fae2c66177362d25e6f1ce80"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#a89faff70fae2c66177362d25e6f1ce80">setColor</a> (<a class="el" href="class_n_r_e_1_1_micro_1_1_color.php">Color</a> const &amp;color)</td></tr>
<tr class="separator:a89faff70fae2c66177362d25e6f1ce80"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae0422cf79e9fc3a07ef687cf36c4047e"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#ae0422cf79e9fc3a07ef687cf36c4047e">setColor</a> (<a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php">ObservedData</a>&lt; <a class="el" href="class_n_r_e_1_1_micro_1_1_color.php">Color</a> &gt; const &amp;color)</td></tr>
<tr class="separator:ae0422cf79e9fc3a07ef687cf36c4047e"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a848d4d85905377c7217d487d2cfc2715"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#a848d4d85905377c7217d487d2cfc2715">setColor</a> (LedId id, <a class="el" href="class_n_r_e_1_1_micro_1_1_color.php">Color</a> const &amp;color)</td></tr>
<tr class="separator:a848d4d85905377c7217d487d2cfc2715"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a78d0285e5ad30402d7b603873edb58eb"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#a78d0285e5ad30402d7b603873edb58eb">setColor</a> (LedId id, <a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php">ObservedData</a>&lt; <a class="el" href="class_n_r_e_1_1_micro_1_1_color.php">Color</a> &gt; const &amp;color)</td></tr>
<tr class="separator:a78d0285e5ad30402d7b603873edb58eb"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a5a9be90b32784cabe694d932ed6b5b18"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#a5a9be90b32784cabe694d932ed6b5b18">setColorHandle</a> (std::function&lt; void(<a class="el" href="class_n_r_e_1_1_micro_1_1_color.php">Color</a> &amp;)&gt; handle)</td></tr>
<tr class="separator:a5a9be90b32784cabe694d932ed6b5b18"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a7e62b5418e28db6f4b03a8f5a2e9e319"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#a7e62b5418e28db6f4b03a8f5a2e9e319">setColorHandle</a> (LedId id, std::function&lt; void(<a class="el" href="class_n_r_e_1_1_micro_1_1_color.php">Color</a> &amp;)&gt; handle)</td></tr>
<tr class="separator:a7e62b5418e28db6f4b03a8f5a2e9e319"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8ab26b698dca92db0e453ba2faf4ee1a"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#a8ab26b698dca92db0e453ba2faf4ee1a">setEffect</a> (<a class="el" href="class_n_r_e_1_1_micro_1_1_effect.php">Effect</a> *effect)</td></tr>
<tr class="separator:a8ab26b698dca92db0e453ba2faf4ee1a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a1ef118da5781f891295f46efef4cde34"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#a1ef118da5781f891295f46efef4cde34">setup</a> (<a class="el" href="class_n_r_e_1_1_micro_1_1_color.php">Color</a> const &amp;startUpColor=BLACK)</td></tr>
<tr class="separator:a1ef118da5781f891295f46efef4cde34"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a1682d49827b1228f5b5dbc3462131e5e"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#a1682d49827b1228f5b5dbc3462131e5e">loop</a> ()</td></tr>
<tr class="separator:a1682d49827b1228f5b5dbc3462131e5e"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aba2b3832cb7fa133b46382cfe5a1eae7"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_micro_1_1_led.php">Led</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#aba2b3832cb7fa133b46382cfe5a1eae7">operator[]</a> (LedId index)</td></tr>
<tr class="separator:aba2b3832cb7fa133b46382cfe5a1eae7"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a5dd923c1d697f5f994197b66d65e2bdb"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_micro_1_1_led.php">Led</a> const &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#a5dd923c1d697f5f994197b66d65e2bdb">operator[]</a> (LedId index) const </td></tr>
<tr class="separator:a5dd923c1d697f5f994197b66d65e2bdb"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af8599c37e356d3241e95adabe71a23b0"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php">LedController</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#af8599c37e356d3241e95adabe71a23b0">operator=</a> (<a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php">LedController</a> const &amp;ctr)=delete</td></tr>
<tr class="separator:af8599c37e356d3241e95adabe71a23b0"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a85d9c8e7c514a43ed972734248eb541e"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php">LedController</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#a85d9c8e7c514a43ed972734248eb541e">operator=</a> (<a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php">LedController</a> &amp;&amp;ctr)=delete</td></tr>
<tr class="separator:a85d9c8e7c514a43ed972734248eb541e"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>Manage access to a led component. </p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="aca90a1d766338cd467cf927063643c99"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Micro::LedController::LedController </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>No default constructor </p>

</div>
</div>
<a class="anchor" id="afe2029cf34f87b8422d70af72a5ab753"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Micro::LedController::LedController </td>
          <td>(</td>
          <td class="paramtype">LedId&#160;</td>
          <td class="paramname"><em>nb</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">Pin&#160;</td>
          <td class="paramname"><em>pin</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">neoPixelType&#160;</td>
          <td class="paramname"><em>type</em> = <code>NEO_GRB&#160;+&#160;NEO_KHZ800</code>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Construct the led controller </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">nb</td><td>the number of controlled led </td></tr>
    <tr><td class="paramname">pin</td><td>the leds strip pin </td></tr>
    <tr><td class="paramname">type</td><td>the leds type </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="aff6899eab59d46ee21e03f3c9d126963"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Micro::LedController::LedController </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php">LedController</a> const &amp;&#160;</td>
          <td class="paramname"><em>ctr</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy forbidden </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">ctr</td><td>the controller to copy </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="af096ed8232cd981f1d29d2d15ee97deb"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Micro::LedController::LedController </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php">LedController</a> &amp;&amp;&#160;</td>
          <td class="paramname"><em>ctr</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move forbidden </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">ctr</td><td>the controller to move </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a1c564c610021c5c9f24dfa8a61ea6faa"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">NRE::Micro::LedController::~LedController </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php" title="Manage access to a led component. ">LedController</a> Deconstructor </p>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="a82eab1bb15dc21d04b5754d268ab8871"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_micro_1_1_led.php">LedController::Iterator</a> NRE::Micro::LedController::begin </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>an iterator on the first element </dd></dl>

</div>
</div>
<a class="anchor" id="aeb0448b85aa79b202cac30fd94bb4e90"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_micro_1_1_led.php">LedController::ConstIterator</a> NRE::Micro::LedController::begin </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>a const iterator on the first element </dd></dl>

</div>
</div>
<a class="anchor" id="a73545f2926f3129379eef377c7123498"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_micro_1_1_led.php">LedController::ConstIterator</a> NRE::Micro::LedController::cbegin </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>a const iterator on the first element </dd></dl>

</div>
</div>
<a class="anchor" id="a1a2cecffbe7a62ec3a352dbdb0e3a302"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_micro_1_1_led.php">LedController::ConstIterator</a> NRE::Micro::LedController::cend </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>a const iterator on the end of the container </dd></dl>

</div>
</div>
<a class="anchor" id="a14e9ce5ae98856abdef002abf9b6bde1"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_micro_1_1_led.php">LedController::Iterator</a> NRE::Micro::LedController::end </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>an iterator on the end of the container </dd></dl>

</div>
</div>
<a class="anchor" id="a9a34c7cebe81aeda12baa868ebc30ea7"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_micro_1_1_led.php">LedController::ConstIterator</a> NRE::Micro::LedController::end </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>a const iterator on the end of the container </dd></dl>

</div>
</div>
<a class="anchor" id="a1682d49827b1228f5b5dbc3462131e5e"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Micro::LedController::loop </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>The controller's loop </p>

</div>
</div>
<a class="anchor" id="af8599c37e356d3241e95adabe71a23b0"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php">LedController</a>&amp; NRE::Micro::LedController::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php">LedController</a> const &amp;&#160;</td>
          <td class="paramname"><em>ctr</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy assign forbidden </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">ctr</td><td>the controller to copy </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="a85d9c8e7c514a43ed972734248eb541e"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php">LedController</a>&amp; NRE::Micro::LedController::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php">LedController</a> &amp;&amp;&#160;</td>
          <td class="paramname"><em>ctr</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move assign forbidden </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">ctr</td><td>the controller to move </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="aba2b3832cb7fa133b46382cfe5a1eae7"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_micro_1_1_led.php">Led</a> &amp; NRE::Micro::LedController::operator[] </td>
          <td>(</td>
          <td class="paramtype">LedId&#160;</td>
          <td class="paramname"><em>index</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Access a particular element without bound checking </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">index</td><td>the element index </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the corresponding element </dd></dl>

</div>
</div>
<a class="anchor" id="a5dd923c1d697f5f994197b66d65e2bdb"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_micro_1_1_led.php">Led</a> const &amp; NRE::Micro::LedController::operator[] </td>
          <td>(</td>
          <td class="paramtype">LedId&#160;</td>
          <td class="paramname"><em>index</em></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Access a particular element without bound checking </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">index</td><td>the element index </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the corresponding element </dd></dl>

</div>
</div>
<a class="anchor" id="a89faff70fae2c66177362d25e6f1ce80"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Micro::LedController::setColor </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php">Color</a> const &amp;&#160;</td>
          <td class="paramname"><em>color</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Set all leds color (and turn them on) </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">color</td><td>the new color </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="ae0422cf79e9fc3a07ef687cf36c4047e"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Micro::LedController::setColor </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php">ObservedData</a>&lt; <a class="el" href="class_n_r_e_1_1_micro_1_1_color.php">Color</a> &gt; const &amp;&#160;</td>
          <td class="paramname"><em>color</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Set all leds color (and turn them on) </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">color</td><td>the new color </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a848d4d85905377c7217d487d2cfc2715"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Micro::LedController::setColor </td>
          <td>(</td>
          <td class="paramtype">LedId&#160;</td>
          <td class="paramname"><em>id</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php">Color</a> const &amp;&#160;</td>
          <td class="paramname"><em>color</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Set a led color (and turn it on) </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">id</td><td>the led id </td></tr>
    <tr><td class="paramname">color</td><td>the new color </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a78d0285e5ad30402d7b603873edb58eb"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Micro::LedController::setColor </td>
          <td>(</td>
          <td class="paramtype">LedId&#160;</td>
          <td class="paramname"><em>id</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php">ObservedData</a>&lt; <a class="el" href="class_n_r_e_1_1_micro_1_1_color.php">Color</a> &gt; const &amp;&#160;</td>
          <td class="paramname"><em>color</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Set a led color (and turn it on) </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">id</td><td>the led id </td></tr>
    <tr><td class="paramname">color</td><td>the new color </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a5a9be90b32784cabe694d932ed6b5b18"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Micro::LedController::setColorHandle </td>
          <td>(</td>
          <td class="paramtype">std::function&lt; void(<a class="el" href="class_n_r_e_1_1_micro_1_1_color.php">Color</a> &amp;)&gt;&#160;</td>
          <td class="paramname"><em>handle</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Set a color handle for all leds </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">handle</td><td>the new handler </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a7e62b5418e28db6f4b03a8f5a2e9e319"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Micro::LedController::setColorHandle </td>
          <td>(</td>
          <td class="paramtype">LedId&#160;</td>
          <td class="paramname"><em>id</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">std::function&lt; void(<a class="el" href="class_n_r_e_1_1_micro_1_1_color.php">Color</a> &amp;)&gt;&#160;</td>
          <td class="paramname"><em>handle</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Set a color handle for a given led </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">id</td><td>the led id </td></tr>
    <tr><td class="paramname">handle</td><td>the new handler </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a8ab26b698dca92db0e453ba2faf4ee1a"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Micro::LedController::setEffect </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_micro_1_1_effect.php">Effect</a> *&#160;</td>
          <td class="paramname"><em>effect</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Set the light effect </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">effect</td><td>the new effect </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a1ef118da5781f891295f46efef4cde34"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Micro::LedController::setup </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_micro_1_1_color.php">Color</a> const &amp;&#160;</td>
          <td class="paramname"><em>startUpColor</em> = <code>BLACK</code></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Setup the controller </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">startUpColor</td><td>the startup color for all leds </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="ab91228876528d9d66b1aa35b078b78e1"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Micro::LedController::turnOff </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Turn all leds off </p>

</div>
</div>
<a class="anchor" id="a7829273c294972a1dcdc4e18e4cada12"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Micro::LedController::turnOff </td>
          <td>(</td>
          <td class="paramtype">LedId&#160;</td>
          <td class="paramname"><em>id</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Turn a led off </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">id</td><td>the led id </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a0b8a39b1a9e132de0f7c2fc5127e8ab0"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Micro::LedController::turnOn </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Turn all leds on </p>

</div>
</div>
<a class="anchor" id="a7f94593a8c490635293b7264f78b00a9"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Micro::LedController::turnOn </td>
          <td>(</td>
          <td class="paramtype">LedId&#160;</td>
          <td class="paramname"><em>id</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Turn a led on with it's saved color </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">id</td><td>the led id </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<hr/>The documentation for this class was generated from the following files:<ul>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-Micro/src/LED/Controller/<a class="el" href="_n_r_e___led_controller_8hpp_source.php">NRE_LedController.hpp</a></li>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-Micro/src/LED/Controller/<a class="el" href="_n_r_e___led_controller_inl_8hpp_source.php">NRE_LedControllerInl.hpp</a></li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
