<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Micro: NRE::Micro::ObservedData&lt; T &gt; Class Template Reference</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>Micro</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php">ObservedData</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="class_n_r_e_1_1_micro_1_1_observed_data-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">NRE::Micro::ObservedData&lt; T &gt; Class Template Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>Represent an observed data by the internal ROM if used, allowing an automatic update between RAM and ROM.  
 <a href="class_n_r_e_1_1_micro_1_1_observed_data.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="_n_r_e___rom_manager_8hpp_source.php">NRE_RomManager.hpp</a>&gt;</code></p>
<div class="dynheader">
Inheritance diagram for NRE::Micro::ObservedData&lt; T &gt;:</div>
<div class="dyncontent">
 <div class="center">
  <img src="class_n_r_e_1_1_micro_1_1_observed_data.png" usemap="#NRE::Micro::ObservedData_3C_20T_20_3E_map" alt=""/>
  <map id="NRE::Micro::ObservedData_3C_20T_20_3E_map" name="NRE::Micro::ObservedData&lt; T &gt;_map">
<area href="class_n_r_e_1_1_micro_1_1_abstract_data.php" title="Represent an abstract data. " alt="NRE::Micro::AbstractData" shape="rect" coords="0,0,195,24"/>
</map>
 </div></div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:ab206accc4946fb61c4e6f400c707e54c"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php#ab206accc4946fb61c4e6f400c707e54c">ObservedData</a> ()</td></tr>
<tr class="separator:ab206accc4946fb61c4e6f400c707e54c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a39840504a2dcdde7342ed7d79035c59d"><td class="memTemplParams" colspan="2">template&lt;class... Args&gt; </td></tr>
<tr class="memitem:a39840504a2dcdde7342ed7d79035c59d"><td class="memTemplItemLeft" align="right" valign="top">&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php#a39840504a2dcdde7342ed7d79035c59d">ObservedData</a> (Args &amp;&amp;...args)</td></tr>
<tr class="separator:a39840504a2dcdde7342ed7d79035c59d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad121e35abe75a1a8b8ab43a33fe1517d"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php#ad121e35abe75a1a8b8ab43a33fe1517d">ObservedData</a> (<a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php">ObservedData</a> const &amp;d)=default</td></tr>
<tr class="separator:ad121e35abe75a1a8b8ab43a33fe1517d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:abc19deb348e88c9b397a49f2f732686f"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php#abc19deb348e88c9b397a49f2f732686f">ObservedData</a> (<a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php">ObservedData</a> &amp;&amp;d)=default</td></tr>
<tr class="separator:abc19deb348e88c9b397a49f2f732686f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a6637913e8e42efad032d35db11c064ad"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php#a6637913e8e42efad032d35db11c064ad">~ObservedData</a> ()=default</td></tr>
<tr class="separator:a6637913e8e42efad032d35db11c064ad"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac6e7dc7c3ed3996279d9f2d3b87a1e14"><td class="memItemLeft" align="right" valign="top">uint32_t&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php#ac6e7dc7c3ed3996279d9f2d3b87a1e14">getSize</a> () const </td></tr>
<tr class="separator:ac6e7dc7c3ed3996279d9f2d3b87a1e14"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a31c5da057567efa27459fed706756764"><td class="memItemLeft" align="right" valign="top">T &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php#a31c5da057567efa27459fed706756764">get</a> ()</td></tr>
<tr class="separator:a31c5da057567efa27459fed706756764"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aff025bb7f4f1a2eb56849035f117e77e"><td class="memItemLeft" align="right" valign="top">T const &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php#aff025bb7f4f1a2eb56849035f117e77e">get</a> () const </td></tr>
<tr class="separator:aff025bb7f4f1a2eb56849035f117e77e"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a2527354b4a42cdd8ca2a13b3a1bfdb10"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php#a2527354b4a42cdd8ca2a13b3a1bfdb10">setHandle</a> (std::function&lt; void(T &amp;)&gt; h)</td></tr>
<tr class="separator:a2527354b4a42cdd8ca2a13b3a1bfdb10"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae31524de97b82aaa75dad2f17a93b5db"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php#ae31524de97b82aaa75dad2f17a93b5db">update</a> ()</td></tr>
<tr class="separator:ae31524de97b82aaa75dad2f17a93b5db"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8133192991e7b9147b7fa60cb5ca8b1b"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php">ObservedData</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php#a8133192991e7b9147b7fa60cb5ca8b1b">operator=</a> (<a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php">ObservedData</a> const &amp;d)=default</td></tr>
<tr class="separator:a8133192991e7b9147b7fa60cb5ca8b1b"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af5cdfe061d29cacb5a75fb8d4cde419b"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php">ObservedData</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php#af5cdfe061d29cacb5a75fb8d4cde419b">operator=</a> (<a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php">ObservedData</a> &amp;&amp;d)=default</td></tr>
<tr class="separator:af5cdfe061d29cacb5a75fb8d4cde419b"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a4cc8da2e5a78b07b832b918269f965f2"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php">ObservedData</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php#a4cc8da2e5a78b07b832b918269f965f2">operator=</a> (T const &amp;d)</td></tr>
<tr class="separator:a4cc8da2e5a78b07b832b918269f965f2"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a06f3611468d03b1ca19a8136ca83348d"><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php">ObservedData</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php#a06f3611468d03b1ca19a8136ca83348d">operator=</a> (T &amp;&amp;d)</td></tr>
<tr class="separator:a06f3611468d03b1ca19a8136ca83348d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:adfa097178973c2022a07a3e9a0e26441"><td class="memTemplParams" colspan="2"><a class="anchor" id="adfa097178973c2022a07a3e9a0e26441"></a>
template&lt;&gt; </td></tr>
<tr class="memitem:adfa097178973c2022a07a3e9a0e26441"><td class="memTemplItemLeft" align="right" valign="top">uint32_t&#160;</td><td class="memTemplItemRight" valign="bottom"><b>getSize</b> () const</td></tr>
<tr class="separator:adfa097178973c2022a07a3e9a0e26441"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="inherit_header pub_methods_class_n_r_e_1_1_micro_1_1_abstract_data"><td colspan="2" onclick="javascript:toggleInherit('pub_methods_class_n_r_e_1_1_micro_1_1_abstract_data')"><img src="closed.png" alt="-"/>&#160;Public Member Functions inherited from <a class="el" href="class_n_r_e_1_1_micro_1_1_abstract_data.php">NRE::Micro::AbstractData</a></td></tr>
<tr class="memitem:ace46a0e36fc28878ffa0e26c7bd27a10 inherit pub_methods_class_n_r_e_1_1_micro_1_1_abstract_data"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_micro_1_1_abstract_data.php#ace46a0e36fc28878ffa0e26c7bd27a10">AbstractData</a> ()=default</td></tr>
<tr class="separator:ace46a0e36fc28878ffa0e26c7bd27a10 inherit pub_methods_class_n_r_e_1_1_micro_1_1_abstract_data"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><h3>template&lt;class T&gt;<br />
class NRE::Micro::ObservedData&lt; T &gt;</h3>

<p>Represent an observed data by the internal ROM if used, allowing an automatic update between RAM and ROM. </p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="ab206accc4946fb61c4e6f400c707e54c"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T &gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php">NRE::Micro::ObservedData</a>&lt; T &gt;::<a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php">ObservedData</a> </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>No default contructor </p>

</div>
</div>
<a class="anchor" id="a39840504a2dcdde7342ed7d79035c59d"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T &gt; </div>
<div class="memtemplate">
template&lt;class... Args&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php">NRE::Micro::ObservedData</a>&lt; T &gt;::<a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php">ObservedData</a> </td>
          <td>(</td>
          <td class="paramtype">Args &amp;&amp;...&#160;</td>
          <td class="paramname"><em>args</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Create the data from the object address </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">args</td><td>the object construction arguments </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="ad121e35abe75a1a8b8ab43a33fe1517d"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php">NRE::Micro::ObservedData</a>&lt; T &gt;::<a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php">ObservedData</a> </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php">ObservedData</a>&lt; T &gt; const &amp;&#160;</td>
          <td class="paramname"><em>d</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy d into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">d</td><td>the data to copy </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="abc19deb348e88c9b397a49f2f732686f"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php">NRE::Micro::ObservedData</a>&lt; T &gt;::<a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php">ObservedData</a> </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php">ObservedData</a>&lt; T &gt; &amp;&amp;&#160;</td>
          <td class="paramname"><em>d</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move d into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">d</td><td>the data to move </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a6637913e8e42efad032d35db11c064ad"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php">NRE::Micro::ObservedData</a>&lt; T &gt;::~<a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php">ObservedData</a> </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php" title="Represent an observed data by the internal ROM if used, allowing an automatic update between RAM and ...">ObservedData</a> Deconstructor </p>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="a31c5da057567efa27459fed706756764"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T &gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">T &amp; <a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php">NRE::Micro::ObservedData</a>&lt; T &gt;::get </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the internal object </dd></dl>

</div>
</div>
<a class="anchor" id="aff025bb7f4f1a2eb56849035f117e77e"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T &gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">T const &amp; <a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php">NRE::Micro::ObservedData</a>&lt; T &gt;::get </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the internal object </dd></dl>

</div>
</div>
<a class="anchor" id="ac6e7dc7c3ed3996279d9f2d3b87a1e14"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T &gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">uint32_t <a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php">NRE::Micro::ObservedData</a>&lt; T &gt;::getSize </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>the object size </dd></dl>

</div>
</div>
<a class="anchor" id="a8133192991e7b9147b7fa60cb5ca8b1b"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php">ObservedData</a>&amp; <a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php">NRE::Micro::ObservedData</a>&lt; T &gt;::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php">ObservedData</a>&lt; T &gt; const &amp;&#160;</td>
          <td class="paramname"><em>d</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copy assign d into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">d</td><td>the data to copy </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="af5cdfe061d29cacb5a75fb8d4cde419b"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php">ObservedData</a>&amp; <a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php">NRE::Micro::ObservedData</a>&lt; T &gt;::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php">ObservedData</a>&lt; T &gt; &amp;&amp;&#160;</td>
          <td class="paramname"><em>d</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Move assign d into this </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">d</td><td>the data to move </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="a4cc8da2e5a78b07b832b918269f965f2"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php">ObservedData</a>&lt; T &gt; &amp; <a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php">NRE::Micro::ObservedData</a>&lt; T &gt;::operator= </td>
          <td>(</td>
          <td class="paramtype">T const &amp;&#160;</td>
          <td class="paramname"><em>d</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Assign the given data internally </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">d</td><td>the data to assign </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="a06f3611468d03b1ca19a8136ca83348d"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php">ObservedData</a>&lt; T &gt; &amp; <a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php">NRE::Micro::ObservedData</a>&lt; T &gt;::operator= </td>
          <td>(</td>
          <td class="paramtype">T &amp;&amp;&#160;</td>
          <td class="paramname"><em>d</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Assign the given data internally </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">d</td><td>the data to assign </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>the reference of himself </dd></dl>

</div>
</div>
<a class="anchor" id="a2527354b4a42cdd8ca2a13b3a1bfdb10"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T&gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void <a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php">NRE::Micro::ObservedData</a>&lt; T &gt;::setHandle </td>
          <td>(</td>
          <td class="paramtype">std::function&lt; void(T &amp;)&gt;&#160;</td>
          <td class="paramname"><em>h</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Set the data handler </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">h</td><td>the new handler </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="ae31524de97b82aaa75dad2f17a93b5db"></a>
<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T &gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void <a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php">NRE::Micro::ObservedData</a>&lt; T &gt;::update </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Update internally the data </p>

</div>
</div>
<hr/>The documentation for this class was generated from the following files:<ul>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-Micro/src/ROM/Manager/<a class="el" href="_n_r_e___rom_manager_8hpp_source.php">NRE_RomManager.hpp</a></li>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-Micro/src/ROM/Manager/<a class="el" href="_n_r_e___observed_data_inl_8hpp_source.php">NRE_ObservedDataInl.hpp</a></li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
