<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Micro: Member List</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>Micro</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php">LedController</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE::Micro::LedController Member List</div>  </div>
</div><!--header-->
<div class="contents">

<p>This is the complete list of members for <a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php">NRE::Micro::LedController</a>, including all inherited members.</p>
<table class="directory">
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#a82eab1bb15dc21d04b5754d268ab8871">begin</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php">NRE::Micro::LedController</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#aeb0448b85aa79b202cac30fd94bb4e90">begin</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php">NRE::Micro::LedController</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#a73545f2926f3129379eef377c7123498">cbegin</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php">NRE::Micro::LedController</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#a1a2cecffbe7a62ec3a352dbdb0e3a302">cend</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php">NRE::Micro::LedController</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr bgcolor="#f0f0f0" class="even"><td class="entry"><b>ConstIterator</b> typedef (defined in <a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php">NRE::Micro::LedController</a>)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php">NRE::Micro::LedController</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#a14e9ce5ae98856abdef002abf9b6bde1">end</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php">NRE::Micro::LedController</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#a9a34c7cebe81aeda12baa868ebc30ea7">end</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php">NRE::Micro::LedController</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#acf67ef0f630bfc74d85ea0bb75e19c2c">getCount</a>() const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php">NRE::Micro::LedController</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr bgcolor="#f0f0f0" class="even"><td class="entry"><b>Iterator</b> typedef (defined in <a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php">NRE::Micro::LedController</a>)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php">NRE::Micro::LedController</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#aca90a1d766338cd467cf927063643c99">LedController</a>()=delete</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php">NRE::Micro::LedController</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#afe2029cf34f87b8422d70af72a5ab753">LedController</a>(LedId nb, Pin pin, neoPixelType type=NEO_GRB+NEO_KHZ800)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php">NRE::Micro::LedController</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#aff6899eab59d46ee21e03f3c9d126963">LedController</a>(LedController const &amp;ctr)=delete</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php">NRE::Micro::LedController</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#af096ed8232cd981f1d29d2d15ee97deb">LedController</a>(LedController &amp;&amp;ctr)=delete</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php">NRE::Micro::LedController</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#a1682d49827b1228f5b5dbc3462131e5e">loop</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php">NRE::Micro::LedController</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#af8599c37e356d3241e95adabe71a23b0">operator=</a>(LedController const &amp;ctr)=delete</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php">NRE::Micro::LedController</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#a85d9c8e7c514a43ed972734248eb541e">operator=</a>(LedController &amp;&amp;ctr)=delete</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php">NRE::Micro::LedController</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#aba2b3832cb7fa133b46382cfe5a1eae7">operator[]</a>(LedId index)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php">NRE::Micro::LedController</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#a5dd923c1d697f5f994197b66d65e2bdb">operator[]</a>(LedId index) const </td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php">NRE::Micro::LedController</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#a89faff70fae2c66177362d25e6f1ce80">setColor</a>(Color const &amp;color)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php">NRE::Micro::LedController</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#ae0422cf79e9fc3a07ef687cf36c4047e">setColor</a>(ObservedData&lt; Color &gt; const &amp;color)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php">NRE::Micro::LedController</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#a848d4d85905377c7217d487d2cfc2715">setColor</a>(LedId id, Color const &amp;color)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php">NRE::Micro::LedController</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#a78d0285e5ad30402d7b603873edb58eb">setColor</a>(LedId id, ObservedData&lt; Color &gt; const &amp;color)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php">NRE::Micro::LedController</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#a5a9be90b32784cabe694d932ed6b5b18">setColorHandle</a>(std::function&lt; void(Color &amp;)&gt; handle)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php">NRE::Micro::LedController</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#a7e62b5418e28db6f4b03a8f5a2e9e319">setColorHandle</a>(LedId id, std::function&lt; void(Color &amp;)&gt; handle)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php">NRE::Micro::LedController</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#a8ab26b698dca92db0e453ba2faf4ee1a">setEffect</a>(Effect *effect)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php">NRE::Micro::LedController</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#a1ef118da5781f891295f46efef4cde34">setup</a>(Color const &amp;startUpColor=BLACK)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php">NRE::Micro::LedController</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#ab91228876528d9d66b1aa35b078b78e1">turnOff</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php">NRE::Micro::LedController</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#a7829273c294972a1dcdc4e18e4cada12">turnOff</a>(LedId id)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php">NRE::Micro::LedController</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#a0b8a39b1a9e132de0f7c2fc5127e8ab0">turnOn</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php">NRE::Micro::LedController</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#a7f94593a8c490635293b7264f78b00a9">turnOn</a>(LedId id)</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php">NRE::Micro::LedController</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#a1c564c610021c5c9f24dfa8a61ea6faa">~LedController</a>()</td><td class="entry"><a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php">NRE::Micro::LedController</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
</table></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
