<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Micro: File List</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li class="current"><a href="files.php"><span>File&#160;List</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="headertitle">
<div class="title">File List</div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock">Here is a list of all documented files with brief descriptions:</div><div class="directory">
<div class="levels">[detail level <span onclick="javascript:toggleLevel(1);">1</span><span onclick="javascript:toggleLevel(2);">2</span><span onclick="javascript:toggleLevel(3);">3</span><span onclick="javascript:toggleLevel(4);">4</span>]</div><table class="directory">
<tr id="row_0_" class="even"><td class="entry"><span style="width:0px;display:inline-block;">&#160;</span><span id="arr_0_" class="arrow" onclick="toggleFolder('0_')">&#9660;</span><span id="img_0_" class="iconfopen" onclick="toggleFolder('0_')">&#160;</span><a class="el" href="dir_68267d1309a1af8e8297ef4c3efbcdba.php" target="_self">src</a></td><td class="desc"></td></tr>
<tr id="row_0_0_"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span id="arr_0_0_" class="arrow" onclick="toggleFolder('0_0_')">&#9660;</span><span id="img_0_0_" class="iconfopen" onclick="toggleFolder('0_0_')">&#160;</span><a class="el" href="dir_a2f0e5642e47e7ed59fe0f0829eafb5f.php" target="_self">Core</a></td><td class="desc"></td></tr>
<tr id="row_0_0_0_" class="even"><td class="entry"><span style="width:32px;display:inline-block;">&#160;</span><span id="arr_0_0_0_" class="arrow" onclick="toggleFolder('0_0_0_')">&#9660;</span><span id="img_0_0_0_" class="iconfopen" onclick="toggleFolder('0_0_0_')">&#160;</span><a class="el" href="dir_b00fbd6cf7f8e36694ce8c1205bd4029.php" target="_self">Module</a></td><td class="desc"></td></tr>
<tr id="row_0_0_0_0_"><td class="entry"><span style="width:64px;display:inline-block;">&#160;</span><span class="icondoc"></span><a class="el" href="_n_r_e___abstract_module_8cpp.php" target="_self">NRE_AbstractModule.cpp</a></td><td class="desc">Implementation of <a class="el" href="namespace_micro.php" title="Micro&#39;s API. ">Micro</a>'s API's Core Object : AbstractModule </td></tr>
<tr id="row_0_0_0_1_" class="even"><td class="entry"><span style="width:64px;display:inline-block;">&#160;</span><a href="_n_r_e___abstract_module_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___abstract_module_8hpp.php" target="_self">NRE_AbstractModule.hpp</a></td><td class="desc">Declaration of <a class="el" href="namespace_micro.php" title="Micro&#39;s API. ">Micro</a>'s API's Core Object : AbstractModule </td></tr>
<tr id="row_0_0_0_2_"><td class="entry"><span style="width:64px;display:inline-block;">&#160;</span><a href="_n_r_e___module_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___module_8hpp.php" target="_self">NRE_Module.hpp</a></td><td class="desc">Declaration of <a class="el" href="namespace_micro.php" title="Micro&#39;s API. ">Micro</a>'s API's Core Object : Module </td></tr>
<tr id="row_0_0_1_" class="even"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><a href="_core_2_n_r_e___core_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_core_2_n_r_e___core_8hpp.php" target="_self">NRE_Core.hpp</a></td><td class="desc">Declaration of <a class="el" href="namespace_micro.php" title="Micro&#39;s API. ">Micro</a>'s API's Core </td></tr>
<tr id="row_0_0_2_"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><a href="_n_r_e___core_inl_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___core_inl_8hpp.php" target="_self">NRE_CoreInl.hpp</a></td><td class="desc">Implmenetation of <a class="el" href="namespace_micro.php" title="Micro&#39;s API. ">Micro</a>'s API's Core </td></tr>
<tr id="row_0_1_" class="even"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span id="arr_0_1_" class="arrow" onclick="toggleFolder('0_1_')">&#9660;</span><span id="img_0_1_" class="iconfopen" onclick="toggleFolder('0_1_')">&#160;</span><a class="el" href="dir_0bb4bacb73d7f86c6a963ab22a4f5c20.php" target="_self">Header</a></td><td class="desc"></td></tr>
<tr id="row_0_1_0_"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><a href="_header_2_n_r_e___core_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_header_2_n_r_e___core_8hpp.php" target="_self">NRE_Core.hpp</a></td><td class="desc">Declaration of <a class="el" href="namespace_micro.php" title="Micro&#39;s API. ">Micro</a>'s API's Core Header </td></tr>
<tr id="row_0_1_1_" class="even"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><a href="_n_r_e___led_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___led_8hpp.php" target="_self">NRE_Led.hpp</a></td><td class="desc">Declaration of <a class="el" href="namespace_micro.php" title="Micro&#39;s API. ">Micro</a>'s API's LED Header </td></tr>
<tr id="row_0_1_2_"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><a href="_n_r_e___micro_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___micro_8hpp.php" target="_self">NRE_Micro.hpp</a></td><td class="desc">Declaration of <a class="el" href="namespace_micro.php" title="Micro&#39;s API. ">Micro</a>'s API's Header </td></tr>
<tr id="row_0_1_3_" class="even"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><a href="_n_r_e___rom_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___rom_8hpp.php" target="_self">NRE_Rom.hpp</a></td><td class="desc">Declaration of <a class="el" href="namespace_micro.php" title="Micro&#39;s API. ">Micro</a>'s API's ROM Header </td></tr>
<tr id="row_0_1_4_"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><a href="_n_r_e___web_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___web_8hpp.php" target="_self">NRE_Web.hpp</a></td><td class="desc">Declaration of <a class="el" href="namespace_micro.php" title="Micro&#39;s API. ">Micro</a>'s API's Web Header </td></tr>
<tr id="row_0_1_5_" class="even"><td class="entry"><span style="width:48px;display:inline-block;">&#160;</span><a href="_n_r_e___wi_fi_8hpp_source.php"><span class="icondoc"></span></a><b>NRE_WiFi.hpp</b></td><td class="desc"></td></tr>
<tr id="row_0_2_"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span id="arr_0_2_" class="arrow" onclick="toggleFolder('0_2_')">&#9660;</span><span id="img_0_2_" class="iconfopen" onclick="toggleFolder('0_2_')">&#160;</span><a class="el" href="dir_6b864641f3cab9a7d09fa51df47d12f6.php" target="_self">LED</a></td><td class="desc"></td></tr>
<tr id="row_0_2_0_" class="even"><td class="entry"><span style="width:32px;display:inline-block;">&#160;</span><span id="arr_0_2_0_" class="arrow" onclick="toggleFolder('0_2_0_')">&#9660;</span><span id="img_0_2_0_" class="iconfopen" onclick="toggleFolder('0_2_0_')">&#160;</span><a class="el" href="dir_d56c61f09457f71bc4acfb7a407e9ce0.php" target="_self">Color</a></td><td class="desc"></td></tr>
<tr id="row_0_2_0_0_"><td class="entry"><span style="width:64px;display:inline-block;">&#160;</span><a href="_n_r_e___color_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___color_8hpp.php" target="_self">NRE_Color.hpp</a></td><td class="desc">Declaration of <a class="el" href="namespace_micro.php" title="Micro&#39;s API. ">Micro</a>'s API's Object : Color </td></tr>
<tr id="row_0_2_0_1_" class="even"><td class="entry"><span style="width:64px;display:inline-block;">&#160;</span><a href="_n_r_e___color_inl_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___color_inl_8hpp.php" target="_self">NRE_ColorInl.hpp</a></td><td class="desc">Implementation of <a class="el" href="namespace_micro.php" title="Micro&#39;s API. ">Micro</a>'s API's Object : Color </td></tr>
<tr id="row_0_2_1_"><td class="entry"><span style="width:32px;display:inline-block;">&#160;</span><span id="arr_0_2_1_" class="arrow" onclick="toggleFolder('0_2_1_')">&#9660;</span><span id="img_0_2_1_" class="iconfopen" onclick="toggleFolder('0_2_1_')">&#160;</span><a class="el" href="dir_57532afd96e118b5b73bacfc38254880.php" target="_self">Controller</a></td><td class="desc"></td></tr>
<tr id="row_0_2_1_0_" class="even"><td class="entry"><span style="width:64px;display:inline-block;">&#160;</span><a href="_n_r_e___led_controller_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___led_controller_8hpp.php" target="_self">NRE_LedController.hpp</a></td><td class="desc">Declaration of <a class="el" href="namespace_micro.php" title="Micro&#39;s API. ">Micro</a>'s API's Object : LedController </td></tr>
<tr id="row_0_2_1_1_"><td class="entry"><span style="width:64px;display:inline-block;">&#160;</span><a href="_n_r_e___led_controller_inl_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___led_controller_inl_8hpp.php" target="_self">NRE_LedControllerInl.hpp</a></td><td class="desc">Implementation of <a class="el" href="namespace_micro.php" title="Micro&#39;s API. ">Micro</a>'s API's Object : LedController </td></tr>
<tr id="row_0_2_1_2_" class="even"><td class="entry"><span style="width:64px;display:inline-block;">&#160;</span><a href="_n_r_e___led_inl_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___led_inl_8hpp.php" target="_self">NRE_LedInl.hpp</a></td><td class="desc">Implementation of <a class="el" href="namespace_micro.php" title="Micro&#39;s API. ">Micro</a>'s API's Object : Led </td></tr>
<tr id="row_0_2_2_"><td class="entry"><span style="width:32px;display:inline-block;">&#160;</span><span id="arr_0_2_2_" class="arrow" onclick="toggleFolder('0_2_2_')">&#9660;</span><span id="img_0_2_2_" class="iconfopen" onclick="toggleFolder('0_2_2_')">&#160;</span><a class="el" href="dir_14280b194263e09dcc6a357b683f8443.php" target="_self">Effect</a></td><td class="desc"></td></tr>
<tr id="row_0_2_2_0_" class="even"><td class="entry"><span style="width:64px;display:inline-block;">&#160;</span><a href="_n_r_e___effect_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___effect_8hpp.php" target="_self">NRE_Effect.hpp</a></td><td class="desc">Declaration of <a class="el" href="namespace_micro.php" title="Micro&#39;s API. ">Micro</a>'s API's Object : Effect </td></tr>
<tr id="row_0_2_2_1_"><td class="entry"><span style="width:64px;display:inline-block;">&#160;</span><a href="_n_r_e___fix_effect_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___fix_effect_8hpp.php" target="_self">NRE_FixEffect.hpp</a></td><td class="desc">Declaration of <a class="el" href="namespace_micro.php" title="Micro&#39;s API. ">Micro</a>'s API's Object : FixEffect </td></tr>
<tr id="row_0_2_2_2_" class="even"><td class="entry"><span style="width:64px;display:inline-block;">&#160;</span><a href="_n_r_e___wave_effect_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___wave_effect_8hpp.php" target="_self">NRE_WaveEffect.hpp</a></td><td class="desc">Declaration of <a class="el" href="namespace_micro.php" title="Micro&#39;s API. ">Micro</a>'s API's Object : WaveEffect </td></tr>
<tr id="row_0_2_3_"><td class="entry"><span style="width:32px;display:inline-block;">&#160;</span><span id="arr_0_2_3_" class="arrow" onclick="toggleFolder('0_2_3_')">&#9660;</span><span id="img_0_2_3_" class="iconfopen" onclick="toggleFolder('0_2_3_')">&#160;</span><a class="el" href="dir_a164b43b90bb7e8c56f5aba4d3c7529c.php" target="_self">Manager</a></td><td class="desc"></td></tr>
<tr id="row_0_2_3_0_" class="even"><td class="entry"><span style="width:64px;display:inline-block;">&#160;</span><a href="_n_r_e___led_manager_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___led_manager_8hpp.php" target="_self">NRE_LedManager.hpp</a></td><td class="desc">Declaration of <a class="el" href="namespace_micro.php" title="Micro&#39;s API. ">Micro</a>'s API's Object : LedManager </td></tr>
<tr id="row_0_2_3_1_"><td class="entry"><span style="width:64px;display:inline-block;">&#160;</span><a href="_n_r_e___led_manager_inl_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___led_manager_inl_8hpp.php" target="_self">NRE_LedManagerInl.hpp</a></td><td class="desc">Implementation of <a class="el" href="namespace_micro.php" title="Micro&#39;s API. ">Micro</a>'s API's Object : LedManager </td></tr>
<tr id="row_0_3_" class="even"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span id="arr_0_3_" class="arrow" onclick="toggleFolder('0_3_')">&#9660;</span><span id="img_0_3_" class="iconfopen" onclick="toggleFolder('0_3_')">&#160;</span><a class="el" href="dir_b8c575fbce9e88769cd973c21567fab3.php" target="_self">ROM</a></td><td class="desc"></td></tr>
<tr id="row_0_3_0_"><td class="entry"><span style="width:32px;display:inline-block;">&#160;</span><span id="arr_0_3_0_" class="arrow" onclick="toggleFolder('0_3_0_')">&#9660;</span><span id="img_0_3_0_" class="iconfopen" onclick="toggleFolder('0_3_0_')">&#160;</span><a class="el" href="dir_6fd6a1e3d1cabd12d4d22f426f330e02.php" target="_self">Manager</a></td><td class="desc"></td></tr>
<tr id="row_0_3_0_0_" class="even"><td class="entry"><span style="width:64px;display:inline-block;">&#160;</span><a href="_n_r_e___observed_data_inl_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___observed_data_inl_8hpp.php" target="_self">NRE_ObservedDataInl.hpp</a></td><td class="desc">Implementation of <a class="el" href="namespace_micro.php" title="Micro&#39;s API. ">Micro</a>'s API's Core Object : ObservedData </td></tr>
<tr id="row_0_3_0_1_"><td class="entry"><span style="width:64px;display:inline-block;">&#160;</span><a href="_n_r_e___rom_manager_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___rom_manager_8hpp.php" target="_self">NRE_RomManager.hpp</a></td><td class="desc">Declaration of <a class="el" href="namespace_micro.php" title="Micro&#39;s API. ">Micro</a>'s API's Object : RomManager </td></tr>
<tr id="row_0_3_0_2_" class="even"><td class="entry"><span style="width:64px;display:inline-block;">&#160;</span><a href="_n_r_e___rom_manager_inl_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___rom_manager_inl_8hpp.php" target="_self">NRE_RomManagerInl.hpp</a></td><td class="desc">Implementation of <a class="el" href="namespace_micro.php" title="Micro&#39;s API. ">Micro</a>'s API's Object : RomManager </td></tr>
<tr id="row_0_4_"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span id="arr_0_4_" class="arrow" onclick="toggleFolder('0_4_')">&#9660;</span><span id="img_0_4_" class="iconfopen" onclick="toggleFolder('0_4_')">&#160;</span><a class="el" href="dir_2f7b293845ef2dc4967d47cb94f137d6.php" target="_self">Web</a></td><td class="desc"></td></tr>
<tr id="row_0_4_0_" class="even"><td class="entry"><span style="width:32px;display:inline-block;">&#160;</span><span id="arr_0_4_0_" class="arrow" onclick="toggleFolder('0_4_0_')">&#9660;</span><span id="img_0_4_0_" class="iconfopen" onclick="toggleFolder('0_4_0_')">&#160;</span><a class="el" href="dir_5fb43b3d5c0b969c19995fcd4c7ae70a.php" target="_self">Manager</a></td><td class="desc"></td></tr>
<tr id="row_0_4_0_0_"><td class="entry"><span style="width:64px;display:inline-block;">&#160;</span><a href="_n_r_e___web_manager_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___web_manager_8hpp.php" target="_self">NRE_WebManager.hpp</a></td><td class="desc">Declaration of <a class="el" href="namespace_micro.php" title="Micro&#39;s API. ">Micro</a>'s API's Object : WebManager </td></tr>
<tr id="row_0_4_0_1_" class="even"><td class="entry"><span style="width:64px;display:inline-block;">&#160;</span><a href="_n_r_e___web_manager_inl_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___web_manager_inl_8hpp.php" target="_self">NRE_WebManagerInl.hpp</a></td><td class="desc">Implementation of <a class="el" href="namespace_micro.php" title="Micro&#39;s API. ">Micro</a>'s API's Object : WebManager </td></tr>
<tr id="row_0_5_"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><span id="arr_0_5_" class="arrow" onclick="toggleFolder('0_5_')">&#9660;</span><span id="img_0_5_" class="iconfopen" onclick="toggleFolder('0_5_')">&#160;</span><a class="el" href="dir_e5889a8f6e66136a451bc59a49215add.php" target="_self">WiFi</a></td><td class="desc"></td></tr>
<tr id="row_0_5_0_" class="even"><td class="entry"><span style="width:32px;display:inline-block;">&#160;</span><span id="arr_0_5_0_" class="arrow" onclick="toggleFolder('0_5_0_')">&#9660;</span><span id="img_0_5_0_" class="iconfopen" onclick="toggleFolder('0_5_0_')">&#160;</span><a class="el" href="dir_12c5bfa1a1339ec11c81ed7328743586.php" target="_self">Manager</a></td><td class="desc"></td></tr>
<tr id="row_0_5_0_0_"><td class="entry"><span style="width:64px;display:inline-block;">&#160;</span><a href="_n_r_e___wi_fi_manager_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___wi_fi_manager_8hpp.php" target="_self">NRE_WiFiManager.hpp</a></td><td class="desc">Declaration of <a class="el" href="namespace_micro.php" title="Micro&#39;s API. ">Micro</a>'s API's Object : WiFiManager </td></tr>
<tr id="row_0_5_0_1_" class="even"><td class="entry"><span style="width:64px;display:inline-block;">&#160;</span><a href="_n_r_e___wi_fi_manager_inl_8hpp_source.php"><span class="icondoc"></span></a><a class="el" href="_n_r_e___wi_fi_manager_inl_8hpp.php" target="_self">NRE_WiFiManagerInl.hpp</a></td><td class="desc">Implementation of <a class="el" href="namespace_micro.php" title="Micro&#39;s API. ">Micro</a>'s API's Object : WiFiManager </td></tr>
</table>
</div><!-- directory -->
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
