<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Micro: Class Members</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li class="current"><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
  <div id="navrow3" class="tabs2">
    <ul class="tablist">
      <li class="current"><a href="functions.php"><span>All</span></a></li>
      <li><a href="functions_func.php"><span>Functions</span></a></li>
      <li><a href="functions_vars.php"><span>Variables</span></a></li>
    </ul>
  </div>
  <div id="navrow4" class="tabs3">
    <ul class="tablist">
      <li><a href="#index_a"><span>a</span></a></li>
      <li><a href="#index_b"><span>b</span></a></li>
      <li><a href="#index_c"><span>c</span></a></li>
      <li><a href="#index_e"><span>e</span></a></li>
      <li><a href="#index_f"><span>f</span></a></li>
      <li><a href="#index_g"><span>g</span></a></li>
      <li><a href="#index_l"><span>l</span></a></li>
      <li><a href="#index_m"><span>m</span></a></li>
      <li><a href="#index_n"><span>n</span></a></li>
      <li><a href="#index_o"><span>o</span></a></li>
      <li><a href="#index_p"><span>p</span></a></li>
      <li><a href="#index_r"><span>r</span></a></li>
      <li><a href="#index_s"><span>s</span></a></li>
      <li><a href="#index_t"><span>t</span></a></li>
      <li><a href="#index_u"><span>u</span></a></li>
      <li><a href="#index_w"><span>w</span></a></li>
      <li class="current"><a href="#index_0x7e"><span>~</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="contents">
<div class="textblock">Here is a list of all documented class members with links to the class documentation for each member:</div>

<h3><a class="anchor" id="index_a"></a>- a -</h3><ul>
<li>AbstractData()
: <a class="el" href="class_n_r_e_1_1_micro_1_1_abstract_data.php#ace46a0e36fc28878ffa0e26c7bd27a10">NRE::Micro::AbstractData</a>
</li>
<li>AbstractModule()
: <a class="el" href="class_n_r_e_1_1_micro_1_1_abstract_module.php#aa3db66bc689eb07168e52157e6cf1702">NRE::Micro::AbstractModule</a>
</li>
<li>add()
: <a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#a30db23a789e19edbe1547c1f3b38f85c">NRE::Micro::MicroManager</a>
</li>
<li>addController()
: <a class="el" href="class_n_r_e_1_1_micro_1_1_led_manager.php#aa778378bc85b3894103d1eabb5a80cd3">NRE::Micro::LedManager</a>
</li>
<li>addHandle()
: <a class="el" href="class_n_r_e_1_1_micro_1_1_web_manager.php#a6ea119278f71be42f465f72f2aceb499">NRE::Micro::WebManager</a>
</li>
<li>addKnownNetwork()
: <a class="el" href="class_n_r_e_1_1_micro_1_1_wi_fi_manager.php#a3ccf7a64ec6ee3718b2eddf18c687c15">NRE::Micro::WiFiManager</a>
</li>
<li>addModule()
: <a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#aea38fe1e1b792700bc032cb8471ab028">NRE::Micro::MicroManager</a>
</li>
</ul>


<h3><a class="anchor" id="index_b"></a>- b -</h3><ul>
<li>begin()
: <a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#a82eab1bb15dc21d04b5754d268ab8871">NRE::Micro::LedController</a>
</li>
</ul>


<h3><a class="anchor" id="index_c"></a>- c -</h3><ul>
<li>cbegin()
: <a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#a73545f2926f3129379eef377c7123498">NRE::Micro::LedController</a>
</li>
<li>cend()
: <a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#a1a2cecffbe7a62ec3a352dbdb0e3a302">NRE::Micro::LedController</a>
</li>
<li>Color()
: <a class="el" href="class_n_r_e_1_1_micro_1_1_color.php#ad4e3c5aca1fd3a4426d1b222ba3b83c3">NRE::Micro::Color</a>
</li>
<li>counter
: <a class="el" href="class_n_r_e_1_1_micro_1_1_abstract_module.php#a95d15910d0d4e77aa08063fe383ff8dc">NRE::Micro::AbstractModule</a>
</li>
</ul>


<h3><a class="anchor" id="index_e"></a>- e -</h3><ul>
<li>end()
: <a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#a14e9ce5ae98856abdef002abf9b6bde1">NRE::Micro::LedController</a>
</li>
<li>extractB()
: <a class="el" href="class_n_r_e_1_1_micro_1_1_color.php#a95b36171d189b73f635cad6eeb0bc8b4">NRE::Micro::Color</a>
</li>
<li>extractG()
: <a class="el" href="class_n_r_e_1_1_micro_1_1_color.php#ad83102ad4e6250d498e99a6ede2a5051">NRE::Micro::Color</a>
</li>
<li>extractR()
: <a class="el" href="class_n_r_e_1_1_micro_1_1_color.php#ae6f843b4e3974141004b54fccca9978d">NRE::Micro::Color</a>
</li>
</ul>


<h3><a class="anchor" id="index_f"></a>- f -</h3><ul>
<li>FixEffect()
: <a class="el" href="class_n_r_e_1_1_micro_1_1_fix_effect.php#a5fdc41f5b8f1e4ffa942b9e99ff16739">NRE::Micro::FixEffect</a>
</li>
</ul>


<h3><a class="anchor" id="index_g"></a>- g -</h3><ul>
<li>get()
: <a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#a0e8afcf29c4af96d8b26172b9c266879">NRE::Micro::MicroManager</a>
, <a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php#aff025bb7f4f1a2eb56849035f117e77e">NRE::Micro::ObservedData&lt; T &gt;</a>
</li>
<li>getB()
: <a class="el" href="class_n_r_e_1_1_micro_1_1_color.php#a3e3a8e355ee733ac09ae1f10db9b57d0">NRE::Micro::Color</a>
</li>
<li>getColor()
: <a class="el" href="class_n_r_e_1_1_micro_1_1_color.php#a724e75202b5bdfc0b64e5c1b0d9a0e9f">NRE::Micro::Color</a>
, <a class="el" href="class_n_r_e_1_1_micro_1_1_led.php#a144cb7e189a4850cf3f5c045c45d5fab">NRE::Micro::Led</a>
</li>
<li>getController()
: <a class="el" href="class_n_r_e_1_1_micro_1_1_led_manager.php#aa64ef572a79d594e67843ee27bf74b46">NRE::Micro::LedManager</a>
</li>
<li>getCount()
: <a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#acf67ef0f630bfc74d85ea0bb75e19c2c">NRE::Micro::LedController</a>
</li>
<li>getG()
: <a class="el" href="class_n_r_e_1_1_micro_1_1_color.php#a12f1cee974aad505f24f8287f8a970cf">NRE::Micro::Color</a>
</li>
<li>getId()
: <a class="el" href="class_n_r_e_1_1_micro_1_1_module.php#a6d9a8c837f180ffd064224d06d9f42e4">NRE::Micro::Module&lt; SubModule &gt;</a>
</li>
<li>getModule()
: <a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#abae5088c23e05992e055aaa14a332ab9">NRE::Micro::MicroManager</a>
</li>
<li>getR()
: <a class="el" href="class_n_r_e_1_1_micro_1_1_color.php#a990af7dcc72d09ca41de6f8d1277625b">NRE::Micro::Color</a>
</li>
<li>getSize()
: <a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php#ac6e7dc7c3ed3996279d9f2d3b87a1e14">NRE::Micro::ObservedData&lt; T &gt;</a>
</li>
</ul>


<h3><a class="anchor" id="index_l"></a>- l -</h3><ul>
<li>Led()
: <a class="el" href="class_n_r_e_1_1_micro_1_1_led.php#a3d47f7f1317221084b4571ae261c34f8">NRE::Micro::Led</a>
</li>
<li>LedController()
: <a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#af096ed8232cd981f1d29d2d15ee97deb">NRE::Micro::LedController</a>
</li>
<li>LedManager()
: <a class="el" href="class_n_r_e_1_1_micro_1_1_led_manager.php#a98cb708bb00b9eeed825c584428305ab">NRE::Micro::LedManager</a>
</li>
<li>loop()
: <a class="el" href="class_n_r_e_1_1_micro_1_1_abstract_module.php#a62533d0ef5768f92707d413d53fb3904">NRE::Micro::AbstractModule</a>
, <a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#a1682d49827b1228f5b5dbc3462131e5e">NRE::Micro::LedController</a>
, <a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#ae353a1ea48369af4c9783977b2b9995a">NRE::Micro::MicroManager</a>
, <a class="el" href="class_n_r_e_1_1_micro_1_1_web_manager.php#a83547254a117ec8c8f35909759909557">NRE::Micro::WebManager</a>
</li>
<li>loopModules()
: <a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#aa1fce2c43a932cce99e74e8423fe8099">NRE::Micro::MicroManager</a>
</li>
</ul>


<h3><a class="anchor" id="index_m"></a>- m -</h3><ul>
<li>MicroManager()
: <a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#a69fb44d8d24a58ed84866f5be95ee6be">NRE::Micro::MicroManager</a>
</li>
<li>Module()
: <a class="el" href="class_n_r_e_1_1_micro_1_1_module.php#ab8051683526e308ef6d0c878ccfb9fe2">NRE::Micro::Module&lt; SubModule &gt;</a>
</li>
</ul>


<h3><a class="anchor" id="index_n"></a>- n -</h3><ul>
<li>name
: <a class="el" href="struct_n_r_e_1_1_micro_1_1_network.php#ad3a8ea4505079c79e77f3748fc854b85">NRE::Micro::Network</a>
</li>
</ul>


<h3><a class="anchor" id="index_o"></a>- o -</h3><ul>
<li>ObservedData()
: <a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php#ab206accc4946fb61c4e6f400c707e54c">NRE::Micro::ObservedData&lt; T &gt;</a>
</li>
<li>operator=()
: <a class="el" href="class_n_r_e_1_1_micro_1_1_abstract_module.php#a2452ab1a95d5dd5c4305605ed4243492">NRE::Micro::AbstractModule</a>
, <a class="el" href="class_n_r_e_1_1_micro_1_1_color.php#a81e0b2b65ecf8e672ba31f1691a3be75">NRE::Micro::Color</a>
, <a class="el" href="class_n_r_e_1_1_micro_1_1_led.php#a26b3dd23f82e48c2d3c6c367a10e81e3">NRE::Micro::Led</a>
, <a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#af8599c37e356d3241e95adabe71a23b0">NRE::Micro::LedController</a>
, <a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#a04b10ab9a31b149214864888cfec6617">NRE::Micro::MicroManager</a>
, <a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php#a4cc8da2e5a78b07b832b918269f965f2">NRE::Micro::ObservedData&lt; T &gt;</a>
</li>
<li>operator[]()
: <a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#aba2b3832cb7fa133b46382cfe5a1eae7">NRE::Micro::LedController</a>
</li>
</ul>


<h3><a class="anchor" id="index_p"></a>- p -</h3><ul>
<li>pwd
: <a class="el" href="struct_n_r_e_1_1_micro_1_1_network.php#a1b007d38ac2e4fbf2c82297bd5ab1bf3">NRE::Micro::Network</a>
</li>
</ul>


<h3><a class="anchor" id="index_r"></a>- r -</h3><ul>
<li>RotateEffect()
: <a class="el" href="class_n_r_e_1_1_micro_1_1_rotate_effect.php#aa81771165f5a0ef53ce9b63b29ac0f45">NRE::Micro::RotateEffect</a>
</li>
<li>RotateFixEffect()
: <a class="el" href="class_n_r_e_1_1_micro_1_1_rotate_fix_effect.php#adac483f6f3ea2bb5306ee6a87a7fe7fb">NRE::Micro::RotateFixEffect</a>
</li>
<li>run()
: <a class="el" href="class_n_r_e_1_1_micro_1_1_effect.php#a0c17b719e2f4974cfc75ba52b25adb83">NRE::Micro::Effect</a>
, <a class="el" href="class_n_r_e_1_1_micro_1_1_fix_effect.php#a1accc8bbcfbc1ac2fef3e10bb2ed7f2e">NRE::Micro::FixEffect</a>
, <a class="el" href="class_n_r_e_1_1_micro_1_1_rotate_effect.php#ae427f12101dc8334910db2a7c4d34c3e">NRE::Micro::RotateEffect</a>
, <a class="el" href="class_n_r_e_1_1_micro_1_1_rotate_fix_effect.php#a79f9ca1a5b2bee5991558adef2a65341">NRE::Micro::RotateFixEffect</a>
, <a class="el" href="class_n_r_e_1_1_micro_1_1_wave_effect.php#a5f8489eccf165da3f63acc81fdf8e7d5">NRE::Micro::WaveEffect</a>
</li>
</ul>


<h3><a class="anchor" id="index_s"></a>- s -</h3><ul>
<li>setAPOnSetup()
: <a class="el" href="class_n_r_e_1_1_micro_1_1_wi_fi_manager.php#a9a0f001e36e296ed8036456560e741cd">NRE::Micro::WiFiManager</a>
</li>
<li>setB()
: <a class="el" href="class_n_r_e_1_1_micro_1_1_color.php#aafcd2a06071ec32b4f6e7ac9a2d0d6a4">NRE::Micro::Color</a>
</li>
<li>setColor()
: <a class="el" href="class_n_r_e_1_1_micro_1_1_led.php#a84e8281436fa31ffbb4eb39ef6aaba4b">NRE::Micro::Led</a>
, <a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#a89faff70fae2c66177362d25e6f1ce80">NRE::Micro::LedController</a>
</li>
<li>setColorHandle()
: <a class="el" href="class_n_r_e_1_1_micro_1_1_led.php#a2624fb34732b14e2eb7f9880c99786cb">NRE::Micro::Led</a>
, <a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#a5a9be90b32784cabe694d932ed6b5b18">NRE::Micro::LedController</a>
</li>
<li>setEffect()
: <a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#a8ab26b698dca92db0e453ba2faf4ee1a">NRE::Micro::LedController</a>
</li>
<li>setG()
: <a class="el" href="class_n_r_e_1_1_micro_1_1_color.php#a1089d94cf65cff8dac8da2da6af8bcd0">NRE::Micro::Color</a>
</li>
<li>setHandle()
: <a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php#a2527354b4a42cdd8ca2a13b3a1bfdb10">NRE::Micro::ObservedData&lt; T &gt;</a>
</li>
<li>setR()
: <a class="el" href="class_n_r_e_1_1_micro_1_1_color.php#a75ca29d00bb4353423ed452913ebe3f5">NRE::Micro::Color</a>
</li>
<li>setup()
: <a class="el" href="class_n_r_e_1_1_micro_1_1_abstract_module.php#a8f93564ffc4fa3818c765b6eed3ab083">NRE::Micro::AbstractModule</a>
, <a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#a1ef118da5781f891295f46efef4cde34">NRE::Micro::LedController</a>
, <a class="el" href="class_n_r_e_1_1_micro_1_1_led_manager.php#a72b0073aef8f0e38e59fd141d719acc2">NRE::Micro::LedManager</a>
, <a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#a8d9a10df1225539a2dcde55dd7c6ed32">NRE::Micro::MicroManager</a>
, <a class="el" href="class_n_r_e_1_1_micro_1_1_web_manager.php#a0a051633dc4a2f90579ea83819980641">NRE::Micro::WebManager</a>
, <a class="el" href="class_n_r_e_1_1_micro_1_1_wi_fi_manager.php#a4673d981d3a99bf6c6fe0926fb5bb8a6">NRE::Micro::WiFiManager</a>
</li>
<li>setupModules()
: <a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#a39f9b0ec9a1d09b092fb833cf41c32cd">NRE::Micro::MicroManager</a>
</li>
<li>start()
: <a class="el" href="class_n_r_e_1_1_micro_1_1_effect.php#a5369c806d8afbfc2024b66ebcbbc1403">NRE::Micro::Effect</a>
, <a class="el" href="class_n_r_e_1_1_micro_1_1_fix_effect.php#acd3cec3a646da0655464290af02947a5">NRE::Micro::FixEffect</a>
, <a class="el" href="class_n_r_e_1_1_micro_1_1_rotate_effect.php#aaa0cb4d33076af4cd850b953f6bf24af">NRE::Micro::RotateEffect</a>
, <a class="el" href="class_n_r_e_1_1_micro_1_1_rotate_fix_effect.php#a1834123e636878bdcf35c45bd258a407">NRE::Micro::RotateFixEffect</a>
, <a class="el" href="class_n_r_e_1_1_micro_1_1_wave_effect.php#adde9092c877e9b19ab9c416d0f1d4379">NRE::Micro::WaveEffect</a>
</li>
<li>stop()
: <a class="el" href="class_n_r_e_1_1_micro_1_1_effect.php#a146b60fdfbad0c0b02fcbc37fe3c5043">NRE::Micro::Effect</a>
, <a class="el" href="class_n_r_e_1_1_micro_1_1_fix_effect.php#aca4d9553c6b265f7b6f4add0ff1dd3ca">NRE::Micro::FixEffect</a>
, <a class="el" href="class_n_r_e_1_1_micro_1_1_rotate_effect.php#a26a4eac70d0b03d2265c8279de949583">NRE::Micro::RotateEffect</a>
, <a class="el" href="class_n_r_e_1_1_micro_1_1_rotate_fix_effect.php#a0914e8c393cef1837a39110f98e2383e">NRE::Micro::RotateFixEffect</a>
, <a class="el" href="class_n_r_e_1_1_micro_1_1_wave_effect.php#a4cecbf43bd264e786bf42e22734dac98">NRE::Micro::WaveEffect</a>
</li>
</ul>


<h3><a class="anchor" id="index_t"></a>- t -</h3><ul>
<li>turnOff()
: <a class="el" href="class_n_r_e_1_1_micro_1_1_led.php#a922510060cd8947bad521fa47a5ee028">NRE::Micro::Led</a>
, <a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#ab91228876528d9d66b1aa35b078b78e1">NRE::Micro::LedController</a>
</li>
<li>turnOn()
: <a class="el" href="class_n_r_e_1_1_micro_1_1_led.php#a8834d8f177b8ab098b107020de280ef2">NRE::Micro::Led</a>
, <a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#a0b8a39b1a9e132de0f7c2fc5127e8ab0">NRE::Micro::LedController</a>
</li>
</ul>


<h3><a class="anchor" id="index_u"></a>- u -</h3><ul>
<li>update()
: <a class="el" href="class_n_r_e_1_1_micro_1_1_led.php#a25bef4d3e5d9463190c55e4a2bfd447c">NRE::Micro::Led</a>
, <a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php#ae31524de97b82aaa75dad2f17a93b5db">NRE::Micro::ObservedData&lt; T &gt;</a>
</li>
</ul>


<h3><a class="anchor" id="index_w"></a>- w -</h3><ul>
<li>WaveEffect()
: <a class="el" href="class_n_r_e_1_1_micro_1_1_wave_effect.php#ac1a8c8b3ab1e96c06c73a01e039bbe21">NRE::Micro::WaveEffect</a>
</li>
<li>WebManager()
: <a class="el" href="class_n_r_e_1_1_micro_1_1_web_manager.php#a9ecc75f34d80a10da66edf8afbc47fc8">NRE::Micro::WebManager</a>
</li>
<li>WiFiManager()
: <a class="el" href="class_n_r_e_1_1_micro_1_1_wi_fi_manager.php#aadc9cdd35e4905e0a95144439ad579bd">NRE::Micro::WiFiManager</a>
</li>
</ul>


<h3><a class="anchor" id="index_0x7e"></a>- ~ -</h3><ul>
<li>~AbstractModule()
: <a class="el" href="class_n_r_e_1_1_micro_1_1_abstract_module.php#a38f613f697ca8d200a1a270e03967d04">NRE::Micro::AbstractModule</a>
</li>
<li>~LedController()
: <a class="el" href="class_n_r_e_1_1_micro_1_1_led_controller.php#a1c564c610021c5c9f24dfa8a61ea6faa">NRE::Micro::LedController</a>
</li>
<li>~LedManager()
: <a class="el" href="class_n_r_e_1_1_micro_1_1_led_manager.php#aa13e06d999087f6f193f4804419d86a0">NRE::Micro::LedManager</a>
</li>
<li>~MicroManager()
: <a class="el" href="class_n_r_e_1_1_micro_1_1_micro_manager.php#a321ee576959f42775fbde9d4a092f7e2">NRE::Micro::MicroManager</a>
</li>
<li>~Module()
: <a class="el" href="class_n_r_e_1_1_micro_1_1_module.php#ab4e431b60f84d4b499c9315cf4502f4b">NRE::Micro::Module&lt; SubModule &gt;</a>
</li>
<li>~ObservedData()
: <a class="el" href="class_n_r_e_1_1_micro_1_1_observed_data.php#a6637913e8e42efad032d35db11c064ad">NRE::Micro::ObservedData&lt; T &gt;</a>
</li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
